### PR TITLE
Handle logging file inside `wireguard-go`

### PR DESCRIPTION
**Pull request by jvff**
Previously, the `wireguard-go` glue library would use as log output a file descriptor received through FFI. This led to some weird issues, where sometimes the process would run into `EBADF` errors in different places.

This PR changes the logging setup so that instead of receiving a file descriptor, a file path is received instead and the file is handled inside the Go library. If there is already a log file open using the same file path, it is reused. Otherwise, the file is created. If there's a previous file with the same name, it is backed up first.

The file is stored as a global variable, protected by a `RWMutex`. This prevents race conditions if any goroutine tries to log something after or while the file is closed.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)

### CODE REVIEW

**Review by DMarby — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @DMarby, @jvff, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrKm9hC5T9JUuTKPdI:-LsrHO2m4pXMaGZAQmE6:b-3oeaci) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L30)):*
> ```Go
> 
> type FileLogger struct {
>     file **os.File
> ```

Since the values of these are always the same, I think it might make sense to simplify it to something like this?

```
type FileLogger struct {}

func (logger FileLogger) Write(buffer []byte) (int, error) {
    logFileLock.RLock()
    defer logFileLock.RUnlock()

    return logFile.Write(buffer)
}
```
___
*[wireguard-go/libwg.go, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrEwy43AEaU39-SFra:-LsrEwy43AEaU39-SFrb:bhvn4f7) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L47)):*
> ```Go
> 
> var tunnelHandles map[int32]TunnelHandle
> var logFile *os.File
> ```

This is a style nitpick, but it might make sense to group these
```
var (
  logFile *os.File
  logFilePath *string
  logFileLock sync.RWMutex
)
```
___
*[wireguard-go/libwg.go, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrEqju8qC6KOHfRI0L:-LsrEqju8qC6KOHfRI0M:b-hki8in) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L53)):*
> ```Go
> func init() {
> 	device.RoamingDisabled = true
>     logFile = nil
> ```

I don't think you need to explicitly assign these on init, they should be nil already
___
*[wireguard-go/libwg.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrI81BDjBEvvz9XHte:-LsrI81BDjBEvvz9XHtf:bkw6o9n) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L84)):*
> ```Go
> 
> func openLogFile(newLogFilePath string) {
>     if (logFilePath == nil || *logFilePath != newLogFilePath) {
> ```

I don't think this outer if statement should be needed, since we lock the mutex, and then do the same check below?
___
*[wireguard-go/libwg.go, line 95 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrGk_LE9ph2EWcsVaD:-LsrGk_LE9ph2EWcsVaE:bdq76ls) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L95)):*
> ```Go
>             logFilePath = &newLogFilePath
>             backupLogFile(newLogFilePath)
>             logFile, _ = os.Create(newLogFilePath)
> ```

Probably good to handle the error from this?
___
*[wireguard-go/libwg.go, line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrI_A_Eb5Ub01oxRAl:-LsrDYNM0_PvPJYK2PaE:b-f0ts3y) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L111)):*
> ```Go
>     }
> 
>     logger := new(FileLogger)
> ```

Rather then doing new here, you can just create the struct directly:
```
logger := &FileLogger{}
```

This has the benefit of when passing variables, you can set them directly, eg:
```
logger := &FileLogger{
  file: &logFile,
  lock: &logFileLock,
}
```

But as mentioned above, I'm not sure if we need to store these in the struct?
___
*[wireguard-go/libwg.go, line 117 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrIKCNBELgmdBSDjLD:-LsrIKCNBELgmdBSDjLE:b-8wryws) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L117)):*
> ```Go
>     logger.lock = &logFileLock
> 
>     if (level == device.LogLevelDebug) {
> ```

Might be sensible to use a `switch` case here instead?

```
	prefix := ""
	switch level {
	case device.LogLevelDebug:
		prefix = "DEBUG: "
	case device.LogLevelInfo:
		prefix = "INFO: "
	case device.LogLevelError:
		prefix = "ERROR: "
	}
```

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @DMarby, @jvff, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 95 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrGk_LE9ph2EWcsVaD:-LsrRPms4sBPoOpnRhxx:blns3w9) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L95)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

Probably good to handle the error from this?
</blockquote></details>

We just need to ensure that the logging calls will still return without changing any global state. There's really no way to handle this, it's not like we can log the error.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)* status: all files reviewed, 7 unresolved discussions (waiting on @DMarby and @jvff)

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)* status: all files reviewed, 7 unresolved discussions (waiting on @DMarby and @jvff)

___
*[wireguard-go/libwg.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrI81BDjBEvvz9XHte:-LsrPzx247UBcnGwdXyD:brfmn9f) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L84)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

I don't think this outer if statement should be needed, since we lock the mutex, and then do the same check below?
</blockquote></details>

The first check is to avoid acquiring the more expensive write lock. But after locking, we need to make sure the condition is still true since it could have changed while we were waiting.

Not sure if this is just premature optimization though :thinking: 
___
*[wireguard-go/libwg.go, line 95 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrGk_LE9ph2EWcsVaD:-LsrTSMEBrq41vhlzAwi:bnfx5u8) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L95)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We just need to ensure that the logging calls will still return without changing any global state. There's really no way to handle this, it's not like we can log the error.
</blockquote></details>

Yeah. I'm trying to think of a fallback, but the only thing I can think of is to set the `logFile` to `nil` and then check it before logging.

Does this make sense?

**Review by DMarby — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)* status: all files reviewed, 6 unresolved discussions (waiting on @jvff)

___
*[wireguard-go/libwg.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrI81BDjBEvvz9XHte:-LsrU-38Be1UGBwV_Ua5:b-4bpmkh) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L84)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

The first check is to avoid acquiring the more expensive write lock. But after locking, we need to make sure the condition is still true since it could have changed while we were waiting.

Not sure if this is just premature optimization though :thinking: 
</blockquote></details>

I would say acquiring the write lock is likely not expensive enough that it is worth it, especially since this is only called when creating new loggers, but yeah
___
*[wireguard-go/libwg.go, line 95 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrGk_LE9ph2EWcsVaD:-LsrUHmS-XY2dwUdXomU:brzvqki) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L95)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yeah. I'm trying to think of a fallback, but the only thing I can think of is to set the `logFile` to `nil` and then check it before logging.

Does this make sense?
</blockquote></details>

logFile should get set to nil if os.Create errors unless I'm not mistaken, and `Write` won't panic on a nil *os.File, so this should be safe as-is then I believe.

I suppose the only other option would be to propagate this up the call-chain, but I don't think you'd want to return an error in eg wgTurnOnWithFd if this failed, so makes sense to not do anything

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @DMarby and @pinkisemils)

___
*[wireguard-go/libwg.go, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrKm9hC5T9JUuTKPdI:-LsrW-TY6cU8jwEsyQnj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L30)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

Since the values of these are always the same, I think it might make sense to simplify it to something like this?

```
type FileLogger struct {}

func (logger FileLogger) Write(buffer []byte) (int, error) {
    logFileLock.RLock()
    defer logFileLock.RUnlock()

    return logFile.Write(buffer)
}
```


</blockquote></details>

Done.
___
*[wireguard-go/libwg.go, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrEwy43AEaU39-SFra:-LsrWg9D0IeHP4jff9Q1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L47)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

This is a style nitpick, but it might make sense to group these
```
var (
  logFile *os.File
  logFilePath *string
  logFileLock sync.RWMutex
)
```
</blockquote></details>

Done.
___
*[wireguard-go/libwg.go, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrEqju8qC6KOHfRI0L:-LsrWzlTBrE9rnhLdhkG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L53)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

I don't think you need to explicitly assign these on init, they should be nil already
</blockquote></details>

Done.
___
*[wireguard-go/libwg.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrI81BDjBEvvz9XHte:-LsrXGR0AxV-3AFpxrbd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L84)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

I would say acquiring the write lock is likely not expensive enough that it is worth it, especially since this is only called when creating new loggers, but yeah
</blockquote></details>

Done.
___
*[wireguard-go/libwg.go, line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrI_A_Eb5Ub01oxRAl:-LsrXdQY0epzxuprWFzR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L111)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

Rather then doing new here, you can just create the struct directly:
```
logger := &FileLogger{}
```

This has the benefit of when passing variables, you can set them directly, eg:
```
logger := &FileLogger{
  file: &logFile,
  lock: &logFileLock,
}
```

But as mentioned above, I'm not sure if we need to store these in the struct?
</blockquote></details>

Done.
___
*[wireguard-go/libwg.go, line 117 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-LsrIKCNBELgmdBSDjLD:-LsrXpOl-rfzBSzgv-x1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8b4211e578ca074d388b96b6f3aaf97d4b42109d/wireguard-go/libwg.go#L117)):*
<details><summary><i>Previously, DMarby (David Marby) wrote…</i></summary><blockquote>

Might be sensible to use a `switch` case here instead?

```
	prefix := ""
	switch level {
	case device.LogLevelDebug:
		prefix = "DEBUG: "
	case device.LogLevelInfo:
		prefix = "INFO: "
	case device.LogLevelError:
		prefix = "ERROR: "
	}
```
</blockquote></details>

Done.

**Review by DMarby — APPROVED** [review]
Awesome :tada: :lgtm: 

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/42#-:-Lss5plACgURdBIsoMzP:bl9dz7w)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
