### PR TITLE
Add configuration for Linux Arm64 builds

### PR DESCRIPTION
**Pull request by nikitalita**
This adds support for Arm64 builds. The only change necessary for arm64-hosted builds is that GCC doesn't support mcmodel=large on ARM, so that was removed for those.

This only supports Arm64-hosted builds currently, this does not currently support cross-compilation.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/80)

### CODE REVIEW

**Comment by faern** [comment]
Thank you for this contribution! We'll review it. Linux arm64 has been a long term goal, albeit pretty low priority. The problem is that basically everyone who wants arm uses a Raspberry Pi, and they usually run 32 bit OSes still. And this app will not support 32 bit. But this contribution could be useful for those who run an "alternative" OS on their RPi (not stable raspbian)

**Comment by nikitalita** [comment]
> Thank you for this contribution! We'll review it. Linux arm64 has been a long term goal, albeit pretty low priority. The problem is that basically everyone who wants arm uses a Raspberry Pi, and they usually run 32 bit OSes still. And this app will not support 32 bit. But this contribution could be useful for those who run an "alternative" OS on their RPi (not stable raspbian)

I made this primarily to run on the Ubuntu aarch64 port for the raspi 4, which is getting increasingly popular thanks to the 8gb raspi4b.

I'm actually working on 32-bit arm version too; This PR also supports builds on armv7l, and I have preliminary support in the app on my fork here:  https://github.com/nikitalita/mullvadvpn-app/tree/rpc-32bit-support

It compiles and runs but it still needs more testing and cleanup to make sure that the RPC changes I made are stable on 32-bit.

**Comment by faern** [comment]
Sorry, but we are not going to merge or release anything for 32 bit. It's just more overhead than we consider worth it for a target that is in steady decline. It's just a question of time before 64 bit OSes are available to the RPis anyway.

I did not know Ubuntu had an aarch64 port. That's great news :)

**Comment by nikitalita** [comment]
> Sorry, but we are not going to merge or release anything for 32 bit. It's just more overhead than we consider worth it for a target that is in steady decline. It's just a question of time before 64 bit OSes are available to the RPis anyway.

Fair enough, I suppose; when I found that Ubuntu's aarch64 release was stable, I just moved to that for my development.
 
> I did not know Ubuntu had an aarch64 port. That's great news :)

Yes, I've found it works well and is stable, and raspbian's aarch64 port is making steady progress. Given that it's basically a requirement to get more than 4gb of RAM on the new raspi4b 8gb models, there's likely going to be a steady uptick of aarch64 linux users.

**Comment by nikitalita** [comment]
I have the linux aarch64 packages for the app fully working on my branch here: https://github.com/nikitalita/mullvadvpn-app/tree/arm64-test

I've tested these on both aarch64 Ubuntu 21.04 and aarch64 Fedora 34 beta on a raspi4, both are fully tested and working.

I'm going to wait until this gets merged and sorted before PRing since this currently points to my fork for the `binaries` submodule, but it's available if you want to take a look.

**Comment by raksooo** [comment]
Great, code looks good, I'm currently testing this as well. I'll try it out with your branch on the app repository.

**Review by raksooo — CHANGES_REQUESTED** [review]
Sorry for delay! Everything is running well on my end as well and this is almost ready to be merged. Could you update the commit message to be in line with the suggestions [here](https://chris.beams.io/posts/git-commit/)? Maybe something like
```
Add support for Linux Arm64
```

Could you rebase it on latest master as well?

**Comment by nikitalita** [comment]
Ok, done

**Comment by raksooo** [comment]
Thanks! And thanks for the contribution! :+1:

**Comment by nikitalita** [comment]
np; once the binaries are built and committed I'll PR app branch.

**Comment by raksooo** [comment]
We currently don't have a setup for building these on our build servers. We're thinking about whether we should run Arm64 Linux in an emulator or if we should cross compile it on our x86 Linux build server. I'm going to look into cross-compilation first and if it proves too difficult then we'll setup an emulator.

**Comment by nikitalita** [comment]
I've looked into this. The simplest solution I found was to just have a bunch of Raspberry PI 4s and setup github action runners on them. If you search around, there are a few people using QEMU on github actions, so you may want to take a look at that as well. I've found that cross compilation tends to be more trouble than it's worth due to subtle incompatibilities cropping up, so I try to avoid it.

**Pull request merged**
