### PR TITLE
Enable DCO support on Linux

### PR DESCRIPTION
**Pull request by dlon**
This also disables `iproute2`, as it's incompatible with DCO.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`libnl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-NOilbW6EWYGnRZMD-LE:-NOilbW6EWYGnRZMD-LF:b-njkfir) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/9e4b090aa93e3556a313d30ca59b08c3341c62c3/libnl#L1)):*
> ```
> Subproject commit cbafad9ddf24caef5230fef715d34f0539603be0
> ```

This points to latest `main` commit. Are you sure we want that instead of a release tag? There are signed release tags, so unless we need latest upstream git version (I doubt) it feels more stable to depend on a release.
___
*[`libnl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-NOiluah7sHMEgbrM-2g:-NOiluah7sHMEgbrM-2h:bvx6xjw) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/9e4b090aa93e3556a313d30ca59b08c3341c62c3/libnl#L1)):*
> ```
> Subproject commit cbafad9ddf24caef5230fef715d34f0539603be0
> ```

Please add to the readme that whenever this is moved to a new commit the commit/tag should be verified. I guess we can list the gpg fingerprint of the current signer (`49EA7C670E0850E7419514F629C2366E4DFC5728`)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`libnl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-NOilbW6EWYGnRZMD-LE:-NOj5pfI5iCSUCGVAvte:boyexbg) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/9e4b090aa93e3556a313d30ca59b08c3341c62c3/libnl#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This points to latest `main` commit. Are you sure we want that instead of a release tag? There are signed release tags, so unless we need latest upstream git version (I doubt) it feels more stable to depend on a release.
</blockquote></details>

Done. Thanks.
___
*[`libnl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-NOiluah7sHMEgbrM-2g:-NOj5yqj4KxXrn2kzR3F:b-ebrrsy) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/9e4b090aa93e3556a313d30ca59b08c3341c62c3/libnl#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please add to the readme that whenever this is moved to a new commit the commit/tag should be verified. I guess we can list the gpg fingerprint of the current signer (`49EA7C670E0850E7419514F629C2366E4DFC5728`)
</blockquote></details>

Done.

We should probably do the same for `libnftnl` and `libmnl`.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-:-NOj9tBl7iufdpnV-cnD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`libnl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-NOiluah7sHMEgbrM-2g:-NOj9mWl9qD1bHXzSq_I:b-d4o2fw) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/9e4b090aa93e3556a313d30ca59b08c3341c62c3/libnl#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.

We should probably do the same for `libnftnl` and `libmnl`.
</blockquote></details>

True, if they have signatures? But that's scope creep for this PR so let's leave it out for now.

**Review by dlon — COMMENTED** [review]
> Dismissed @faern from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libnl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/102#-NOiluah7sHMEgbrM-2g:-NOjG3dw-c_eIwPOe34p:b-pbdqz3) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/9e4b090aa93e3556a313d30ca59b08c3341c62c3/libnl#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

True, if they have signatures? But that's scope creep for this PR so let's leave it out for now.
</blockquote></details>

Agreed.

**Pull request merged**
