### PR TITLE
Build new OpenSSL binaries for Android

### PR DESCRIPTION
**Pull request by jvff**
This PR updates the build procedure for the Android binaries in order to build with the new OpenSSL version. In summary, with the new OpenSSL version the procedure became simpler and a hack could be removed. However, the actual build was restricted to the libraries since the programs failed compilation. The Android app only uses the libraries, so this is not a problem.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android-build/build.sh, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-LjaaCsk4DHroc81ylMS:-LjaaCslAowGPubiAW3m:brxrrrz) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8a59040a22de82e70b921d8a25e5690a41153107/android-build/build.sh#L10)):*
> ```Shell
> 
> pushd openssl
> ./Configure android-arm64 no-shared -static --prefix=/opt/openssl --openssldir=/opt/openssl ${OPENSSL_CONFIG}
> ```

How come we don't need the `sed -i .... -mandroid...` step any more?

And why are we switching from `android64-aarch64` to `android-arm64`?
___
*[android-build/build.sh, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-LjaaVyP6cSxQ515Prhj:-LjaaVyP6cSxQ515Prhk:b7v5q8f) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8a59040a22de82e70b921d8a25e5690a41153107/android-build/build.sh#L15)):*
> ```Shell
> 
> cp libcrypto.a ../android/libcrypto.a
> cp libssl.a ../android/libssl.a
> ```

We previously copied the C header files. This step seems removed now. How come we don't need them?
___
*[android-build/Dockerfile, line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-Ljaat4H7UDFpC2RBUaB:-Ljaat4I4MJCFZwDq1My:b-ybu4o3) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8a59040a22de82e70b921d8a25e5690a41153107/android-build/Dockerfile#L26)):*
> ```Dockerfile
>     ANDROID_LLVM_TRIPLE="aarch64-linux-android" \
>     ANDROID_C_COMPILER="/opt/android/toolchains/android28-aarch64/bin/aarch64-linux-android28-clang" \
>     ANDROID_NDK_HOME="/opt/android/android-ndk-r19b" \
> ```

Our main repo README still tell users to download NDK r20. If this requirement changes then please update the main README accordingly.

**Comment by jvff** [comment]
___
*[android-build/build.sh, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-LjaaCsk4DHroc81ylMS:-Ljab2uk-xv-svisCKBn:bw2w59e) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8a59040a22de82e70b921d8a25e5690a41153107/android-build/build.sh#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

How come we don't need the `sed -i .... -mandroid...` step any more?

And why are we switching from `android64-aarch64` to `android-arm64`?
</blockquote></details>

These are changes due to the new Android build scripts present in the newer OpenSSL version. The `-mandroid` flag is now set by that script, and they have streamlined their architecture list so that it closer matches Android's naming scheme (i.e., `arm`, `arm64`, `x86`, `x86_64`).

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[android-build/build.sh, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-LjaaVyP6cSxQ515Prhj:-Ljab5SE9yfMw-kQDwFx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8a59040a22de82e70b921d8a25e5690a41153107/android-build/build.sh#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We previously copied the C header files. This step seems removed now. How come we don't need them?
</blockquote></details>

Done.
___
*[android-build/Dockerfile, line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-Ljaat4H7UDFpC2RBUaB:-LjagEjsEYWfwdvaczQ8:b-t27qll) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/8a59040a22de82e70b921d8a25e5690a41153107/android-build/Dockerfile#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Our main repo README still tell users to download NDK r20. If this requirement changes then please update the main README accordingly.
</blockquote></details>

Sure, I'll update it when I bump the binaries sub-module reference.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-:-Ljal6l7BebuTcPzKjhN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android-build/build.sh, line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-LjakVsYC00U2OxBIhXy:-LjakVsZ0unD96Y_JAkC:b8yet6h) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/e64fb74098c7b22a57106f41856385c83e7a095e/android-build/build.sh#L16)):*
> ```Shell
> mkdir -p ../android/include/openssl
> cp libcrypto.a ../android/libcrypto.a
> cp libssl.a ../android/libssl.a
> ```

Nit, but the filename does have to be repeated in the destination argument (like you have already done for the headers). It can also be condensed to one command `cp lib{ssl,crypto}.a ../android/`

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @faern)

___
*[android-build/build.sh, line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/28#-LjakVsYC00U2OxBIhXy:-LjanRA29a4NaK7c7_3s:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/e64fb74098c7b22a57106f41856385c83e7a095e/android-build/build.sh#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit, but the filename does have to be repeated in the destination argument (like you have already done for the headers). It can also be condensed to one command `cp lib{ssl,crypto}.a ../android/`
</blockquote></details>

Done.

**Pull request merged**
