### PR TITLE
Add compiled openssl

### PR DESCRIPTION
**Pull request by pinkisemils**
I've updated the Makefile and added a batch script so that we can build statically linkable OpenSSL libraries for our Rust code. I've also fixed an issue where our Windows build of OpenVPN would get a config parameter for Linux, which would result in a failed build.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 5 of 10 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 16 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[Makefile, line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZxzcm-lqyJpeDni54:-LGZxzcnAXfgU8SpR0yQ:b-wdke8i) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/Makefile#L30)):*
> ```Makefile
> ifeq ($(UNAME_S),Darwin)
> 	SHARED_LIB_EXT = dylib
> 	TARGET_OUTPUT_DIR = "macos"
> ```

Since we now have this convenient variable. Should we maybe also add so the `windows` and `openvpn` targets copy the openvpn binary into where it should be as a last step as well? For the `windows` target we would not use the variable though, just hardcode `windows/`
___
*[Makefile, line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZxdIE8vmSeG3-2i38:-LGZxdIE8vmSeG3-2i39:b-gnrabn) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/Makefile#L111)):*
> ```Makefile
> 	strip $(BUILD_DIR)/sbin/openvpn
> 
> windows: clean
> ```

This makefile starts doing more and more. I think it would make sense to rename this target to include `openvpn` in the name, like `openvpn_windows` maybe?
___
*[Makefile, line 118 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZxUsG2-fnnjMAXJZ2:-LGZxUsH7zbsqdhL5vP1:b-s8lw7p) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/Makefile#L118)):*
> ```Makefile
> 	ln -sf $(PWD)/openssl $(WINDOWS_BUILDROOT)/$(OPENSSL_VERSION)
> 	ln -sf $(PWD)/openvpn $(WINDOWS_BUILDROOT)/$(OPENVPN_VERSION)
> 	cd openvpn && autoreconf -f -v;
> ```

We have used `;` to join commands in all other places in this makefile. Any reason to use `&&` that is better? Just thinking if we can keep consistency if possible.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 16 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[build-openssl-with-msvc.bat, line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZz0rd8cr9NEbRtER1:-LGZz0re9TlhRon2ZKO1:bw19wmh) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/build-openssl-with-msvc.bat#L7)):*
> ```Batchfile
>   --prefix=%cd%\..\msvc-openssl ^
>   --openssldir=%cd%\..\msvc-openssl ^
>   no-seed ^
> ```

Is there any way in bat to define a free standing variable where we can hold the OpenSSL config? Would be more readable and easier to compare to the *nix version of the same thing.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 10 of 15 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_JpHc3e6wtHOPjsHj:-LG_JpHd5TWOvt9O9i_9:b-pr6mpo) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L1)):*
> ```Markdown
> # Custom Mullvad VPN build of OpenVPN
> ```

If the content is changed to not be OpenVPN specific so should the title I think. Maybe `Custom third party binaries for the Mullvad VPN app"?

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 15 files reviewed, 6 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_KK6w4Z6mcqzEbTFE:-LG_KK6w4Z6mcqzEbTFF:baywlld) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L3)):*
> ```Markdown
> # Custom Mullvad VPN build of OpenVPN
> 
> This repository holds our custom OpenVPN binaries , statically linkable OpenSSL
> ```

There is a space before the comma here.
___
*[README.md, line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_KVP4C5qQsetWuFaR:-LG_KVP4C5qQsetWuFaS:bif099x) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L14)):*
> ```Markdown
> 
> ## Building
> Currently, building is only supported on Debian 9.
> ```

Part of this repository is buildable, and should be built on macOS and Windows. So maybe be more specific, or put this under a `### Linux` title?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 15 files reviewed, 8 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Ko1V810fzfQv4Tfl:-LG_Ko1V810fzfQv4Tfm:bdk8vte) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L20)):*
> ```Markdown
> dependencies installed, as outlined in [OpenVPN's buildslave documentation].
> 
> Building the OpenVPN binary should be as simple as running `make`, which should produce the binary at
> ```

The part about running `make` is not true any more. We removed the `all` target since it now builds so much more. Please update to `make openvpn`.
___
*[README.md, line 21 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Kz6u6y55DGJRDHoZ:-LG_Kz6v04GIeYNLwnMK:b-milf71) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L21)):*
> ```Markdown
> 
> Building the OpenVPN binary should be as simple as running `make`, which should produce the binary at
> `./build/sbin/openvpn`.
> ```

Since it's now automatically copied to the desired destination this can be removed I think.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 15 files reviewed, 10 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_LEjO2PN7wgQBDRIv:-LG_LEjO2PN7wgQBDRIw:bfq7180) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L28)):*
> ```Markdown
> 
> Building `openvpn.exe` for Windows is done by cross-compiling from Linux using a mingw-w64
> toolchain. You need to do this build on a recent Debian or Ubuntu release, one
> ```

Maybe here it makes sense to say "Debian 9" as well? While it likely works on other machines we want to at least for our own builds stick to one distro. Also since it should be really easy to build with our own makefile I don't think we really should encourage going to OpenVPN's build docs, rather just tell people to run the two commands that follow here. If they encounter any problems they can be directed to the official docs.
___
*[README.md, line 39 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_LUoeCmP322nWBvWw:-LG_LUoeCmP322nWBvWx:b-h6dlla) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L39)):*
> ```Markdown
> 1. Compile:
>    ```bash
>    make openvpn/windows
> ```

`openvpn_windows`?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 15 files reviewed, 12 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_MTWI-rVHzWRSug1t:-LG_MTWI-rVHzWRSug1u:b-ce1fpv) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L51)):*
> ```Markdown
> 2017 Community Edition works).
> - [NASM](https://www.nasm.us/)
> To compile OpenSSL for Windows with MSVC, run the following script:
> ```

You need more spacing for the layout to be correct when rendering. You need an empty line between the list and this paragraph. At the moment it's rendered like "NASM To compile ..." as one sentence on the same line.

Have an empty line between paragraphs in general. Same should go for just after this code block here, but that one renders correctly anyway at the moment as well.
___
*[README.md, line 53 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_M2R01mBf8URUD8ti:-LG_M2R01mBf8URUD8tj:b-f0zpbd) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L53)):*
> ```Markdown
> To compile OpenSSL for Windows with MSVC, run the following script:
> ```
> build_openssl_msvc.bat
> ```

Looks like it's called `build-openssl-with-msvc.bat`.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 11 of 15 files reviewed, 11 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[build-openssl-with-msvc.bat, line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZz0rd8cr9NEbRtER1:-LG_Q35K6wZeNb0PirOp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is there any way in bat to define a free standing variable where we can hold the OpenSSL config? Would be more readable and easier to compare to the *nix version of the same thing.
</blockquote></details>

Done.
___
*[Makefile, line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZxzcm-lqyJpeDni54:-LG_Q15H1utE595IJGHV:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/Makefile#L30)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since we now have this convenient variable. Should we maybe also add so the `windows` and `openvpn` targets copy the openvpn binary into where it should be as a last step as well? For the `windows` target we would not use the variable though, just hardcode `windows/`
</blockquote></details>

Done
___
*[Makefile, line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZxdIE8vmSeG3-2i38:-LG_6FDh-BOy1SZjEMxN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/Makefile#L111)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This makefile starts doing more and more. I think it would make sense to rename this target to include `openvpn` in the name, like `openvpn_windows` maybe?
</blockquote></details>

Done.
___
*[Makefile, line 118 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZxUsG2-fnnjMAXJZ2:-LG_QgM24fwJcBShJOTd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/Makefile#L118)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We have used `;` to join commands in all other places in this makefile. Any reason to use `&&` that is better? Just thinking if we can keep consistency if possible.
</blockquote></details>

Done.
___
*[README.md, line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_JpHc3e6wtHOPjsHj:-LG_OsN89zJz94nKFTq3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If the content is changed to not be OpenVPN specific so should the title I think. Maybe `Custom third party binaries for the Mullvad VPN app"?
</blockquote></details>

Done.
___
*[README.md, line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_KK6w4Z6mcqzEbTFE:-LG_OrUg65H-5WbYsdWj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L3)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

There is a space before the comma here.
</blockquote></details>

Done.
___
*[README.md, line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_KVP4C5qQsetWuFaR:-LG_MR2KAHR2Xc15db_q:bdg3212) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Part of this repository is buildable, and should be built on macOS and Windows. So maybe be more specific, or put this under a `### Linux` title?
</blockquote></details>

I'll just remove it as I've referred
___
*[README.md, line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Ko1V810fzfQv4Tfl:-LG_Oqky8wwyHyH8L2uA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The part about running `make` is not true any more. We removed the `all` target since it now builds so much more. Please update to `make openvpn`.
</blockquote></details>

Done.
___
*[README.md, line 21 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Kz6u6y55DGJRDHoZ:-LG_OnsKCKsf6WEp8ItF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L21)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since it's now automatically copied to the desired destination this can be removed I think.
</blockquote></details>

Done.
___
*[README.md, line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_LEjO2PN7wgQBDRIv:-LG_OlnF7ppy2AtLpJWC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe here it makes sense to say "Debian 9" as well? While it likely works on other machines we want to at least for our own builds stick to one distro. Also since it should be really easy to build with our own makefile I don't think we really should encourage going to OpenVPN's build docs, rather just tell people to run the two commands that follow here. If they encounter any problems they can be directed to the official docs.
</blockquote></details>

Done.
___
*[README.md, line 39 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_LUoeCmP322nWBvWw:-LG_OttaBYovsoq7-Ol3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L39)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`openvpn_windows`?
</blockquote></details>

Done.
___
*[README.md, line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_MTWI-rVHzWRSug1t:-LG_NqQG4WwlVZQ8-YPA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L51)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You need more spacing for the layout to be correct when rendering. You need an empty line between the list and this paragraph. At the moment it's rendered like "NASM To compile ..." as one sentence on the same line.

Have an empty line between paragraphs in general. Same should go for just after this code block here, but that one renders correctly anyway at the moment as well.
</blockquote></details>

Done.
___
*[README.md, line 53 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_M2R01mBf8URUD8ti:-LG_OuKCCrxt23v8lHBH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a3b721acc8eb18c383726406cd1a059be4f2b9ed/README.md#L53)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Looks like it's called `build-openssl-with-msvc.bat`.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 12 of 15 files reviewed, 10 unresolved discussions (waiting on @faern)

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[build-openssl-with-msvc.bat, line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZz0rd8cr9NEbRtER1:-LG_SD3Q5i4xvHnsinC6:b1y2g6c) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What does the `-FIWindows.h` flag mean? That looks more like a needed compile flag rather than an OpenSSL option being turned on and off to me.
___
*[README.md, line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_JpHc3e6wtHOPjsHj:-LG_SfpO9kExw8jekP8l:b-ijs8sy) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L1)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`s/binearies/binaries/`

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_JpHc3e6wtHOPjsHj:-LG_TJjp72SibfXrOYqE:b-a72n39) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/README.md#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`s/binearies/binaries/`
</blockquote></details>

Also *the* Mullvad VPN app to be completely correct.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Tolf556aP-MFobCg:-LG_Tolf556aP-MFobCh:b-dzo31c) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/README.md#L50)):*
> ```Markdown
> `make openssl`. To do so, one has to make sure to have all the required build
> dependencies on the build host. To update the statically linkable OpenSSL
> library, run `make update_openssl`.
> ```

Telling people to run `make openssl` *and* `make update_openssl` wastes a lot of compile time. The `openssl` target cleans itself before build anyway, and `update_openssl` depends on `openssl` anyway. So everything built during the first run of `make openssl` will just be thrown away anyway.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_UA6g-74h2LL7TPjD:-LG_UA6g-74h2LL7TPjE:b-wqj003) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/README.md#L49)):*
> ```Markdown
> To build statically linkable OpenSSL libraries on macOS and Linux, just run
> `make openssl`. To do so, one has to make sure to have all the required build
> dependencies on the build host. To update the statically linkable OpenSSL
> ```

It says to install the build dependencies, but does not list which those are or link to any external resources.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[README.md, line 54 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Umwl1dGl3zpvo470:-LG_Umwl1dGl3zpvo471:brwlu1z) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/README.md#L54)):*
> ```Markdown
> 
> ### Windows
> To build the daemon on Windows, one has to build statically linkable OpenSSL libraries.
> ```

First of all the word "daemon" here might be a bit too far from it's home context to be directly recognizable. If it should be mentioned I think "Mullvad VPN daemon" is more appropriate.

Secondly needing statically linkable OpenSSL libraries is not Windows specific, so if this explanation should be in the README it should likely be directly under `##  Building OpenSSL`

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 13 of 15 files reviewed, 6 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[build-openssl-with-msvc.bat, line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZz0rd8cr9NEbRtER1:-LG_Vin20Y1Y1rvbyxgg:b-rorj6e) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What does the `-FIWindows.h` flag mean? That looks more like a needed compile flag rather than an OpenSSL option being turned on and off to me.
</blockquote></details>

What I meant is that it looks like it would fit better directly in the perl call.
___
*[build-openssl-with-msvc.bat, line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_VnDJBp8z_Mm_x_x_:-LG_VnDJBp8z_Mm_x_xa:b-d0ub9k) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/build-openssl-with-msvc.bat#L12)):*
> ```Batchfile
>   no-shared ^
>   -FIWindows.h
> call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
> ```

Is it not possible to have some blank lines? The config floats together very much with the code here.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: 14 of 15 files reviewed, 6 unresolved discussions (waiting on @faern and @pinkisemils)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[build-openssl-with-msvc.bat, line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LGZz0rd8cr9NEbRtER1:-LG_kin4EeZeHV1b4ytb:bs4dlhd) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/77b428ce1a50d4bd21232f0558e360eb9a3f864b/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What I meant is that it looks like it would fit better directly in the perl call.
</blockquote></details>

All arguments which start with a dash will be passed onto the compiler and linker as regular arguments. This arguments makes sure that during the compilation the `Windows.h` header is _in scope_. This is sort of copied from Microsoft's own build script for `OpenSSL`. https://github.com/Microsoft/vcpkg/blob/1b2f75be941e9eed5986c10eb99fd6049490daec/ports/openssl/make-openssl.bat

I've moved it as well.
___
*[build-openssl-with-msvc.bat, line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_VnDJBp8z_Mm_x_x_:-LG_kiND-Y1XSxBKZQUX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/build-openssl-with-msvc.bat#L12)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is it not possible to have some blank lines? The config floats together very much with the code here.
</blockquote></details>

Done.
___
*[README.md, line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_UA6g-74h2LL7TPjD:-LG_bMIVCUWgyrdhajXf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/README.md#L49)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It says to install the build dependencies, but does not list which those are or link to any external resources.
</blockquote></details>

Done.
___
*[README.md, line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-LG_Tolf556aP-MFobCg:-LG_bM0a2CwS4X3uSuSL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/55b61939022f3fa535507c6d882d0a0a2c7485bd/README.md#L50)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Telling people to run `make openssl` *and* `make update_openssl` wastes a lot of compile time. The `openssl` target cleans itself before build anyway, and `update_openssl` depends on `openssl` anyway. So everything built during the first run of `make openssl` will just be thrown away anyway.
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11#-:-LG_mbTJ-Ylh31H5VseU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/11)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
