### PR TITLE
Upgrade OpenVPN to 2.4.8 and OpenSSL to 1.1.1d

### PR DESCRIPTION
**Pull request by faern**
As the title says.

Also upgrades libsodium to 1.0.18 to make it support VS2019.

The newer TAP driver comes in a separate PR from David.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
I have tested this on Windows and macOS both with and without shadowsocks. It seems to work fine.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51#-:-Lu296qFBpuA5vvODhzC:b-tpyegi)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

___
*[Makefile, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51#-Lu29CZBAvfVc8QFAuen:-Lu29CZBAvfVc8QFAueo:bmdpwwz) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5169d45831aa4e292b5fb8b6aa2de866c0eee51e/Makefile#L15)):*
> ```Makefile
> 	--disable-def-auth --disable-pf --disable-pkcs11 --disable-lzo \
> 	--enable-lz4 --enable-ssl --enable-crypto --enable-plugins \
> 	--enable-password-save --enable-socks --enable-http-proxy
> ```

These are invalid options. Some of them has been for multiple releases. But the configure script just warns and we missed it. Now removing all the invalid options. It seems all of these features are built in by default without an option.
___
*[Makefile, line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51#-Lu29NmG6B0oUCBjghNY:-Lu29NmG6B0oUCBjghNZ:b4yi348) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/19b8cd49dd984fd74ee4e75c251c8e3177fda6c9/Makefile#L108)):*
> ```Makefile
> 		EXTRA_OPENSSL_CONFIG="-static-libgcc no-shared $(OPENSSL_CONFIG)" \
> 		EXTRA_TARGET_LDFLAGS="-Wl,-Bstatic" \
> 		OPT_OPENVPN_CFLAGS="-O2 -flto" \
> ```

This is the new amazing speed optimization that the release was talking about. Apparently the Windows releases has been built without any compiler optimization turned on up until now. Also makes the binary smaller.
___
*[Makefile, line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51#-Lu29W971Cay792ewVzg:-Lu29W971Cay792ewVzh:b-f8bzbl) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/19b8cd49dd984fd74ee4e75c251c8e3177fda6c9/Makefile#L114)):*
> ```Makefile
> 		IMAGEROOT="$(BUILD_DIR)" \
> 		./openvpn-build/generic/build
> 	cp openvpn/src/openvpn/openvpn.exe ./x86_64-pc-windows-msvc/
> ```

Oops. Seems to have been forgotten back when we moved to target triple directories.

**Review by dlon — APPROVED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 13 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/51)* status: 13 of 17 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Comment by dlon** [comment]
On my own PC, it complains that libssl-1_1-x64.dll and libcrypto-1_1-x64.dll are missing when I run the daemon. So dynamic linking is used for these libraries.

**Pull request merged**
