### PR TITLE
Add container for building the binaries

### PR DESCRIPTION
**Pull request by dlon**
This can be used for (cross) compiling to all targets (x64 Linux, x64 Windows, aarch64 Linux) except macOS. See the readme and Dockerfile for details.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkBlTCV_uZnPgo-8V:-NOJkBlTCV_uZnPgo-8W:b-7jt9lf) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/51c0b42f5aaa36e35567a934249bfc97744fce6e/Dockerfile#L5)):*
> ```Dockerfile
> #
> # Example using the makefile to cross-compile openvpn for windows:
> # podman run --rm -v .:/build:Z mullvadvpn-app-binaries /bin/sh -c 'make openvpn_windows'
> ```

I don't think we should duplicate the build instructions in too many places. I suggest we have the `podman build` part in the README in the container image section (where it's currently placed) and remove all `podman run` examples from the Dockerfile itself but rather focus on having good instructions in the README for those.
___
*[`Dockerfile` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJfLf59bvymePE_7J3:-NOJfLf59bvymePE_7J4:b-t2pm71) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/51c0b42f5aaa36e35567a934249bfc97744fce6e/Dockerfile#L10)):*
> ```Dockerfile
> # This checksum points to a 10.13-slim image.
> FROM debian@sha256:557ee531b81ce380d012d83b7bb56211572e5d6088d3e21a3caef7d7ed7f718b
> ```

Just for cleanliness I think we should add the recommended labels. Something like:

```
LABEL org.opencontainers.image.source=https://github.com/mullvad/mullvadvpn-app-binaries
LABEL org.opencontainers.image.description="Mullvad VPN app extra binaries build container"
LABEL org.opencontainers.image.licenses=GPL-3.0
```
___
*[`README.md` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkAxXCMXjIumOBCOI:-NOJkAxXCMXjIumOBCOJ:bmpa6r0) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/51c0b42f5aaa36e35567a934249bfc97744fce6e/README.md#L42)):*
> ```Markdown
>    -v ./x86_64-unknown-linux-gnu:/build/x86_64-unknown-linux-gnu:Z \
>    -v ./aarch64-unknown-linux-gnu:/build/aarch64-unknown-linux-gnu:Z \
>    mullvadvpn-app-binaries /bin/sh -c 'make openvpn_windows'
> ```

Please add `-it`, otherwise ctrl-c does not work during builds.
___
*[`README.md` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkd7b0IKP9pfqlUj1:-NOJkd7b0IKP9pfqlUj2:btlid9r) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/51c0b42f5aaa36e35567a934249bfc97744fce6e/README.md#L42)):*
> ```Markdown
>    -v ./x86_64-unknown-linux-gnu:/build/x86_64-unknown-linux-gnu:Z \
>    -v ./aarch64-unknown-linux-gnu:/build/aarch64-unknown-linux-gnu:Z \
>    mullvadvpn-app-binaries /bin/sh -c 'make openvpn_windows'
> ```

This command is genious! But a bit troublesome to copy-paste, and currently only talks about the Windows build. I suggest we remove all `podman run` examples from this container image section, move this brilliant command into a little bash script that takes as first argument linux/windows and builds for that platform. Then under the respective build instructions further down, instruct the user to run that script on Linux and for Windows.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @faern)

___
*[`Dockerfile` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkBlTCV_uZnPgo-8V:-NOKp1YY8Otbf4t69QOf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d72996066cc31e0f7086d90860900b418ad42e1d/Dockerfile#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think we should duplicate the build instructions in too many places. I suggest we have the `podman build` part in the README in the container image section (where it's currently placed) and remove all `podman run` examples from the Dockerfile itself but rather focus on having good instructions in the README for those.
</blockquote></details>

Done.
___
*[`Dockerfile` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJfLf59bvymePE_7J3:-NOKp1q84kE3-i_FTqKD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d72996066cc31e0f7086d90860900b418ad42e1d/Dockerfile#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Just for cleanliness I think we should add the recommended labels. Something like:

```
LABEL org.opencontainers.image.source=https://github.com/mullvad/mullvadvpn-app-binaries
LABEL org.opencontainers.image.description="Mullvad VPN app extra binaries build container"
LABEL org.opencontainers.image.licenses=GPL-3.0
```
</blockquote></details>

Done.
___
*[`README.md` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkAxXCMXjIumOBCOI:-NOKp2sI4QZAV8kD4odF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d72996066cc31e0f7086d90860900b418ad42e1d/README.md#L42)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please add `-it`, otherwise ctrl-c does not work during builds.
</blockquote></details>

Done.
___
*[`README.md` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkd7b0IKP9pfqlUj1:-NOKp3R08q5p5zdMqCJb:bwwv59s) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d72996066cc31e0f7086d90860900b418ad42e1d/README.md#L42)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This command is genious! But a bit troublesome to copy-paste, and currently only talks about the Windows build. I suggest we remove all `podman run` examples from this container image section, move this brilliant command into a little bash script that takes as first argument linux/windows and builds for that platform. Then under the respective build instructions further down, instruct the user to run that script on Linux and for Windows.
</blockquote></details>

What about `TARGET=aarch64-unknown-linux-gnu`? I've moved this command to `container.sh`, but it seems simple enough to just run `./container.sh "make openvpn_windows"`, `./container.sh "make openvpn TARGET=aarch64-unknown-linux-gnu"`, etc. What are your thoughts?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`container.sh` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOWkrQEUPcExK5-RMu:-NOOWkrQEUPcExK5-RMv:b-7e4gyb) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Can we maybe name this script `container-run.sh` to be aligned with the similar script we have in `/building/`? Neither name might be perfect, but that at least describes what it does a slight bit more.
___
*[`container.sh` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOX2qo35J6yAEGjR8A:-NOOX2qp-X_1Y-a_qH7l:bjho114) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Can we add a comment that this assumes you have built an image from the `Dockerfile` in this directory and that it assumes it's named `mullvadvpn-app-binaries`. This script makes some assumptions that are not 100% clear.
___
*[`container.sh` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOIhGM5D-dzwXkTeOO:-NOOIhGM5D-dzwXkTeOP:btcv53s) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L9)):*
> ```Shell
> 
> podman run --rm -it \
>     -v .:/build:O \
> ```

I think Albin has pointed out that it's recommended to always use absolute paths for this even if `.` works. You could simply use `$SCRIPT_DIR` here and not even need to cd into it. The same applies to all mounts below also.
___
*[`container.sh` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOWcHx5AQw_950ws-k:-NOOWcHx5AQw_950ws-l:bqrbrjz) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L13)):*
> ```Shell
>     -v ./x86_64-unknown-linux-gnu:/build/x86_64-unknown-linux-gnu:Z \
>     -v ./aarch64-unknown-linux-gnu:/build/aarch64-unknown-linux-gnu:Z \
>     mullvadvpn-app-binaries /bin/sh -c "$1"
> ```

Any reason to not have `"$@"` be the argument(s) here?
___
*[`README.md` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkd7b0IKP9pfqlUj1:-NOOXR9vBaFkQCn_K1tr:b-oqjkk1) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d72996066cc31e0f7086d90860900b418ad42e1d/README.md#L42)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

What about `TARGET=aarch64-unknown-linux-gnu`? I've moved this command to `container.sh`, but it seems simple enough to just run `./container.sh "make openvpn_windows"`, `./container.sh "make openvpn TARGET=aarch64-unknown-linux-gnu"`, etc. What are your thoughts?
</blockquote></details>

This is fine. But is there any way to not have to quote the command and instead be able to do `./container-run.sh make openvpn`? Because otherwise someone will unavoidably make that mistake, and I doubt the error output will be clear.
___
*[`README.md` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOXi5R8HpP-mhYx_8r:-NOOXi5R8HpP-mhYx_8s:bw3eumx) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/README.md#L30)):*
> ```Markdown
> 
> ```bash
> ./container.sh "make openvpn_windows"
> ```

I still don't think we should talk about container usage here. Remove this and instead under `### Building for Windows` replace the first bullet point with `./container-run.sh make openvpn_windows`. And the same for Linux. We don't need to document both how to build in and outside a container. Better if the instructions for Linux + windows here only talks about the container build IMO.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @faern)

___
*[`README.md` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOJkd7b0IKP9pfqlUj1:-NOOdZTKBXnA2We4997X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d72996066cc31e0f7086d90860900b418ad42e1d/README.md#L42)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is fine. But is there any way to not have to quote the command and instead be able to do `./container-run.sh make openvpn`? Because otherwise someone will unavoidably make that mistake, and I doubt the error output will be clear.
</blockquote></details>

Done.
___
*[`README.md` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOXi5R8HpP-mhYx_8r:-NOOe4_A13Ar1TZZzkQW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/README.md#L30)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I still don't think we should talk about container usage here. Remove this and instead under `### Building for Windows` replace the first bullet point with `./container-run.sh make openvpn_windows`. And the same for Linux. We don't need to document both how to build in and outside a container. Better if the instructions for Linux + windows here only talks about the container build IMO.
</blockquote></details>

Done.
___
*[`container.sh` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOWkrQEUPcExK5-RMu:-NOOdtuQ-_dZgDkD7tdX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we maybe name this script `container-run.sh` to be aligned with the similar script we have in `/building/`? Neither name might be perfect, but that at least describes what it does a slight bit more.
</blockquote></details>

Done.
___
*[`container.sh` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOX2qo35J6yAEGjR8A:-NOOdxjnA_iVL_-DzsLf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we add a comment that this assumes you have built an image from the `Dockerfile` in this directory and that it assumes it's named `mullvadvpn-app-binaries`. This script makes some assumptions that are not 100% clear.
</blockquote></details>

Done.
___
*[`container.sh` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOOWcHx5AQw_950ws-k:-NOOdczb96aKBL1mylRO:bwnp6xg) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a2386e9969f9398c26abc17ed4f809de9dd950d3/container.sh#L13)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Any reason to not have `"$@"` be the argument(s) here?
</blockquote></details>

Done. The arguments need to be passed in as a single string. `$@` gives me multiple args, but `$*` does the trick.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Makefile` line 20 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-NOUujaa3FDGIa_Kert6:-NOUujaa3FDGIa_Kert7:bs0tr3a) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccfc2816322902f1751837331b6059264a939365/Makefile#L20)):*
> ```Makefile
> 	--disable-management --disable-port-share --disable-systemd --disable-dependency-tracking \
> 	--disable-pkcs11 --disable-lzo --disable-plugin-auth-pam --disable-lz4 --enable-plugins \
> 	--enable-comp-stub
> ```

Very nitpick, but I would consider putting all compression related flags on one line.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/101#-:-NOil3_SAS26-Yxvrg9w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
