### PR TITLE
Add wgGetConfig and wgFreePtr to wireguard-go

### PR DESCRIPTION
**Pull request by pinkisemils**
Adding `wgGetConfig` and `wgFreePtr` to `wireguard-go` and `wireguard-go-windows`. These changes enable the daemon to retrieve traffic data from `wireguard-go` which allows it to infer whether a tunnel is working or not.

I've made the code changes and recompiled the libraries for all of our platforms.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)

### CODE REVIEW

**Review by mvd-ows — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf1HcY-gKBd4-NeovF:-Lyf1HcZ5sgFwKrhlCtO:b-napu72) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L4)):*
> ```Go
>  *
>  * Copyright (C) 2017-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
>  */
> ```

You can add another line of copyright information here.
___
*[wireguard-go/libwg.go, line 202 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf1UMl5HdqeMeio8fv:-Lyf1UMm38djWqIVIVfo:b-t5v12a) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L202)):*
> ```Go
> 	handle, ok := tunnelHandles[tunnelHandle]
> 	if !ok {
> 		fmt.Println("Handle not even here lol")
> ```

Perhaps reword the message?
___
*[wireguard-go/libwg.go, line 214 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf3pfk5M40i_8L9aBf:-Lyf3O_60Btddp6GMxwO:b-avny6g) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L214)):*
> ```Go
> 	}
> 	writer.Flush()
> 	return C.CString(settings.String())
> ```

There's no null terminator in the byte buffer, right? And there never will be?
___
*[wireguard-go-windows/libwg.go, line 272 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf4iiX7F9l6P2n0rcq:-Lyf4iiX7F9l6P2n0rcr:b-oemk3m) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go-windows/libwg.go#L272)):*
> ```Go
> 	handle, ok := tunnels[tunnelHandle]
> 	if !ok {
> 		return nil
> ```

Write log entry before returning?
___
*[wireguard-go-windows/libwg.go, line 278 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf4vAmCOjhVl01JnTa:-Lyf4vAmCOjhVl01JnTb:b-oemk3m) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go-windows/libwg.go#L278)):*
> ```Go
> 	writer := bufio.NewWriter(settings)
> 	if err := handle.device.IpcGetOperation(writer); err != nil {
> 		return nil
> ```

Write log entry before returning?

**Review by faern — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: all files reviewed, 5 unresolved discussions (waiting on @mvd-ows and @pinkisemils)

___
*[wireguard-go/libwg.go, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyhcvpH9x4m2BrlE8am:-LyhcvpH9x4m2BrlE8an:b-17568t) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L200)):*
> ```Go
> //export wgGetConfig
> func wgGetConfig(tunnelHandle int32) *C.char {
> 	handle, ok := tunnelHandles[tunnelHandle]
> ```

I have not been very involved in the golang code, so I won't get in too deep. And I see we have done the same thing in other code. But my initial feeling here is that it's confusing to call the *index* `tunnelHandle`.
___
*[wireguard-go/libwg.go, line 214 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf3pfk5M40i_8L9aBf:-LyheNeW9T1lsEnQlBhz:bcwf7ki) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L214)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There's no null terminator in the byte buffer, right? And there never will be?
</blockquote></details>

If it's a "CString" it really sounds like there should be one :thinking: If it's treated as a C String on the Rust side it will expect one at least.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 3 of 13 files reviewed, 5 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 214 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf3pfk5M40i_8L9aBf:-LyiNQz9BPEGT48XZbta:bj450kw) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L214)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If it's a "CString" it really sounds like there should be one :thinking: If it's treated as a C String on the Rust side it will expect one at least.
</blockquote></details>

Certainly. I was referring to the byte buffer holding all data before the C-string is constructed. I was curious if the presence or lack of a null terminator would make a difference and if it's ever an issue at all.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 3 of 13 files reviewed, 5 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyhcvpH9x4m2BrlE8am:-LyiNzJfB_Mt0F_c6yX5:b-pm15gg) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L200)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I have not been very involved in the golang code, so I won't get in too deep. And I see we have done the same thing in other code. But my initial feeling here is that it's confusing to call the *index* `tunnelHandle`.
</blockquote></details>

Why? For all purposes it's a handle that identifies a tunnel instance. It also happens to be a valid index that allows us to quickly locate the correct tunnel data.

The issue is that the global container being used to store tunnel data is incorrectly named.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 3 of 13 files reviewed, 4 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 214 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf3pfk5M40i_8L9aBf:-Lyi2rypB71rzJ9Kz3LX:b-8beiiy) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L214)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Certainly. I was referring to the byte buffer holding all data before the C-string is constructed. I was curious if the presence or lack of a null terminator would make a difference and if it's ever an issue at all.
</blockquote></details>

Even though the [documentation](https://golang.org/cmd/cgo/) doesn't mention it, the string is reallocated and a null termintator is appended. If it wasn't, the Rust code that consumes this would fail.
___
*[wireguard-go-windows/libwg.go, line 272 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf4iiX7F9l6P2n0rcq:-Lyi30QVACtNB803jI5a:b-kiz2nk) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go-windows/libwg.go#L272)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Write log entry before returning?
</blockquote></details>

If there's no handle here, then there's no logger either.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 214 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf3pfk5M40i_8L9aBf:-LyifhlR7hDi6HSN_N2C:b-ps9my6) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L214)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Even though the [documentation](https://golang.org/cmd/cgo/) doesn't mention it, the string is reallocated and a null termintator is appended. If it wasn't, the Rust code that consumes this would fail.
</blockquote></details>

I realize that Rust expects there to be a null terminator. But what I wanted to clear up is whether the terminator is required to be present in the byte buffer that the string is derived from. If it was required to be present, and if the IPC server could plausibly fail to add it, that's something to verify on the end of the IPC client.

But there's no such requirement and I'm happy to resolve the discussion.
___
*[wireguard-go-windows/libwg.go, line 272 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-Lyf4iiX7F9l6P2n0rcq:-LyigfVm4vDkjB5rI_nD:bcn3o5u) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go-windows/libwg.go#L272)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If there's no handle here, then there's no logger either.
</blockquote></details>

Ah, right.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyhcvpH9x4m2BrlE8am:-LyixGJm7NsrCOlOEUEc:b-7hm7t1) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L200)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Why? For all purposes it's a handle that identifies a tunnel instance. It also happens to be a valid index that allows us to quickly locate the correct tunnel data.

The issue is that the global container being used to store tunnel data is incorrectly named.
</blockquote></details>

For all purposes it's an array index that identifies a `TunnelHandle` in a global array of `TunnelHandle`s? Or I might have misunderstood the code.

Isn't the type of `handle` here a `TunnelHandle`? If there is a type named `TunnelHandle` present in the system, I would say it's confusing to name any variable that is not a `TunnelHandle` `tunnelHandle`. I would probably have named it `tunnelHandle_index` or something like that.
___
*[wireguard-go-windows/libwg.go, line 278 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyiyGZy5RFS7yjBgP-c:-LyiyGZy5RFS7yjBgP-d:b-7ioh2p) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a00a3e551edfe881edb1cc6ec633fbf869124caa/wireguard-go-windows/libwg.go#L278)):*
> ```Go
> 	writer := bufio.NewWriter(settings)
> 	if err := tunnel.device.IpcGetOperation(writer); err != nil {
> 		tunnel.logger.Error.Println("Failed to get config for tunel: ", err)
> ```

tunel

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyhcvpH9x4m2BrlE8am:-Lyjm1wt46tWnGxQ5-Po:b9f1v1k) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L200)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

For all purposes it's an array index that identifies a `TunnelHandle` in a global array of `TunnelHandle`s? Or I might have misunderstood the code.

Isn't the type of `handle` here a `TunnelHandle`? If there is a type named `TunnelHandle` present in the system, I would say it's confusing to name any variable that is not a `TunnelHandle` `tunnelHandle`. I would probably have named it `tunnelHandle_index` or something like that.
</blockquote></details>

Too much meta. Yes, the type is also wrongly named. This has been corrected in the Windows version of the code.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @faern, @mvd-ows, and @pinkisemils)

___
*[wireguard-go/libwg.go, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyhcvpH9x4m2BrlE8am:-LyoWYRYCEwrVW4cqAP3:b3wv58a) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/feabcc25bd560a0f90d9b6ed2b4d6303087e279d/wireguard-go/libwg.go#L200)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Too much meta. Yes, the type is also wrongly named. This has been corrected in the Windows version of the code.
</blockquote></details>

The `tunnelHandles` name originates from the original wrapper library for Android/iOS. I don't feel like much is gained by changing the name here.
___
*[wireguard-go-windows/libwg.go, line 278 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/56#-LyiyGZy5RFS7yjBgP-c:-LyoWltS8ZijUo8gwr0P:bs4ywmx) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a00a3e551edfe881edb1cc6ec633fbf869124caa/wireguard-go-windows/libwg.go#L278)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

tunel
</blockquote></details>

This is fixed in the version that is being moved to the main repository.

**Pull request closed without merging**
