### PR TITLE
Remove more OpenSSL things.

### PR DESCRIPTION
**Pull request by pinkisemils**
Since OpenSSL is no longer linked in the daemon, static libraries stored in this repository are redundant. Thus they are removed, and the buildscripts have been adjusted to use the build directory instead of the build artifact output directories for linking OpenSSL.

As I can't seem to get `make openvpn` to work on macOS with and without these changes, I'd greatly appreciate if someone was to build OpenVPN with my changes too, to verify that nothing is broken.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[Makefile, line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M71z5wS7npHK21-j_W8:-M71z5wT01DOhOogTg-H:b99fnij) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/Makefile#L93)):*
> ```Makefile
> 	cp $(BUILD_DIR)/sbin/openvpn $(TARGET_OUTPUT_DIR)/
> 
> openvpn_windows: clean-submodules openssl
> ```

Are you sure it uses the artifacts built by the `openssl` target to link into the Windows binaries? That sounds very strange. I doubt the Linux builds would work on Windows.

Here is where the Windows cross compiling script builds OpenSSL for Windows: https://github.com/mullvad/openvpn-build/blob/530a7fd008713cd36c6fadaf7869c9f1cc9102e0/generic/build#L170-L191
___
*[README.md, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M72-oEq3DmSxXUZyCrN:-M72-oEq3DmSxXUZyCrO:b-o4n1un) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/README.md#L5)):*
> ```Markdown
> This repository holds our custom binaries and build scripts for third party software we need to
> bundle with the Mullvad VPN app: OpenVPN and Shadowsocks for our target platforms, `libmnl` and
> `libnftnl` for Linux.
> ```

Unrelated to this PR. But could you also mention WinTun and the TAP driver, which is also part of this repo?
___
*[README.md, line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M720H505kfj6QO2PmpE:-M720H505kfj6QO2PmpF:b-o0cp3h) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/README.md#L178)):*
> ```Markdown
> 
> To build Shadowsocks, just run `shaodwsocks-windows.bat` from a command prompt that has the Visual
> Studio 2019 build tool environment. The script will compile `libsodium` and `opnessl` statically and
> ```

typo: openssl
___
*[README.md, line 187 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M720UCk1rpRgDKfnWKP:-M720UCk1rpRgDKfnWKQ:b-mvw69o) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/README.md#L187)):*
> ```Markdown
> - [NASM](https://www.nasm.us/), make sure that the tools are in your PATH.
>   If installed with `chocolatey`, to set it up for your current shell, just run
>   the batch script in `C:\Program Files\NASM\nasmpath.bat`.
> ```

Regarding this long list of dependencies... Now we just need to make `shadowsocks-rust` switch over to rustls for crypto :sweat_smile:

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64)* status: all files reviewed, 5 unresolved discussions (waiting on @pinkisemils)

___
*[shadowsocks-windows.bat, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M72EnzC6DAVPC45zGHh:-M72EnzC6DAVPC45zGHi:bddbw47) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/shadowsocks-windows.bat#L43)):*
> ```Batchfile
> cd shadowsocks-rust
>   mkdir .cargo
>   copy ..\win-shadowsocks-cargo-config .cargo\config
> ```

I think you forgot to commit this file?
___
*[shadowsocks-windows.bat, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M72Evo9-C6S6JhyHKEK:-M72Evo9-C6S6JhyHKEL:b-gmpkeh) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/shadowsocks-windows.bat#L45)):*
> ```Batchfile
>   copy ..\win-shadowsocks-cargo-config .cargo\config
>   CARGO_TARGET_DIR=
>   set SODIUM_STATIC="1"
> ```

Any reason some variables get a `set` and `CARGO_TARGET_DIR` does not?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64)* status: 14 of 17 files reviewed, 5 unresolved discussions (waiting on @faern)

___
*[Makefile, line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M71z5wS7npHK21-j_W8:-M72OSt63xAaKa3_89HZ:b-u11aww) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/Makefile#L93)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Are you sure it uses the artifacts built by the `openssl` target to link into the Windows binaries? That sounds very strange. I doubt the Linux builds would work on Windows.

Here is where the Windows cross compiling script builds OpenSSL for Windows: https://github.com/mullvad/openvpn-build/blob/530a7fd008713cd36c6fadaf7869c9f1cc9102e0/generic/build#L170-L191
</blockquote></details>

Nope, this isn't required!
___
*[README.md, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M72-oEq3DmSxXUZyCrN:-M72Opz931QBiPGAaYmR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/README.md#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Unrelated to this PR. But could you also mention WinTun and the TAP driver, which is also part of this repo?
</blockquote></details>

Done.
___
*[README.md, line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M720H505kfj6QO2PmpE:-M72OrmF5GwsTsnAYzLm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/README.md#L178)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

typo: openssl
</blockquote></details>

Done.
___
*[README.md, line 187 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M720UCk1rpRgDKfnWKP:-M72Ml_MAkWUdQHa5szo:be2l6su) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/README.md#L187)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Regarding this long list of dependencies... Now we just need to make `shadowsocks-rust` switch over to rustls for crypto :sweat_smile: 
</blockquote></details>

:sweat_smile: 
___
*[shadowsocks-windows.bat, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M72EnzC6DAVPC45zGHh:-M72MkU33kI3AEmXxDdC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/shadowsocks-windows.bat#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think you forgot to commit this file?
</blockquote></details>

Done.
___
*[shadowsocks-windows.bat, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-M72Evo9-C6S6JhyHKEK:-M72GxynDaKcD5hBjJNJ:b-ch5cjw) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f59f97123c360d16e9cdf73375948b8a70332867/shadowsocks-windows.bat#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Any reason some variables get a `set` and `CARGO_TARGET_DIR` does not?
</blockquote></details>

`CARGO_TARGET_DIR` variable is being unset to do the same thing the Makefile does.

**Review by faern — APPROVED** [review]
:lgtm: :champagne: :tada: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/64#-:-M72P9QN4tBX85C_qiZt:bbmh9ir)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
