### PR TITLE
Fix msvc configuration for OpenSSL

### PR DESCRIPTION
**Pull request by dlon**
There were linker errors, probably because the libraries were using MSVCRT.lib rather than LIBCMT.lib. This was due to a typo in our build script.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
Awesome. Great find! Let's wait with merging this though. I can build and push the new binaries to the same PR so it gets fixed in one go.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-:-LvCYcdW6ktYIk8vy2vp:b-y1jguy)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[build-openssl-with-msvc.bat, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-LvCY_jL15VASa8QqDrg:-LvCY_jL15VASa8QqDrh:bvytv5a) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/14ce537f70e660f8e5ff29a5b969510e6079243a/build-openssl-with-msvc.bat#L5)):*
> ```Batchfile
> set OPENSSL_CONFIG =   enable-capieng ^
>      enable-rfc3779 ^
>      no-ssl2 ^
> ```

Is this not a valid option to pass any longer, or why is it removed?
___
*[build-openssl-with-msvc.bat, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-LvCYKtF-G4yNiRkd76U:-LvCYKtF-G4yNiRkd76V:bso61m5) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/34dc905826325ca9f93ecc1389d2cf02ff101ed7/build-openssl-with-msvc.bat#L19)):*
> ```Batchfile
>   -FIWindows.h
> 
> :: nmake clean
> ```

Commenting out cleaning is something left over from testing I suppose? I guess we want to keep cleaning for real builds?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[build-openssl-with-msvc.bat, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-LvEx3_O8c9DA07LSgmj:-LvEx3_P0pb00vv3coaG:b7cl0zw) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/34dc905826325ca9f93ecc1389d2cf02ff101ed7/build-openssl-with-msvc.bat#L4)):*
> ```Batchfile
> 
> set OPENSSL_CONFIG=enable-capieng ^
>      enable-rfc3779 ^
> ```

Nit, but all these lines are indented with 5(?!) spaces :sweat_smile: Can we change that to 2, since that seems to be what we use for indentation below?

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[build-openssl-with-msvc.bat, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-LvCY_jL15VASa8QqDrg:-LvF-JvKBstQL_ibAC3r:bfbqwvp) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/14ce537f70e660f8e5ff29a5b969510e6079243a/build-openssl-with-msvc.bat#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is this not a valid option to pass any longer, or why is it removed?
</blockquote></details>

It is deprecated.
___
*[build-openssl-with-msvc.bat, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-LvCYKtF-G4yNiRkd76U:-LvF-Uy2BcOx9EAyQghB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/34dc905826325ca9f93ecc1389d2cf02ff101ed7/build-openssl-with-msvc.bat#L19)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Commenting out cleaning is something left over from testing I suppose? I guess we want to keep cleaning for real builds?
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/54#-:-LvF4nieB8usxl_IARaV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
