### PR TITLE
Add OpenVPN 2.4.6 binaries for all three platforms

### PR DESCRIPTION
**Pull request by faern**
Adding my statically linked OpenVPN binaries for all three platforms. If you have the time and energy please test these on the platforms you have access to. So far I have only tested the macOS one, will try Linux as well. But sadly I don't have a working Windows VM at the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4)

### CODE REVIEW

**Comment by pinkisemils** [comment]
Tested the windows binary, it works as expected.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4#-:-LChVkUU7n7h4h5sTeXq:bwhmscw)*

**Comment by jvff** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/4)*

**Pull request merged**
