### PR TITLE
Update OpenSSL to 1.1.1c for Windows

### PR DESCRIPTION
**Pull request by pinkisemils**
I fixed the buildscript for OpenSSL on Windows and built libraries with the currently checked out submodule, which gets us a newer version of OpenSSL on Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[build-openssl-with-msvc.bat, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-LlW4Tdt7L0k_JrkD3oA:-LlW4TduDBvgeIu6NOnQ:buay1nl) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccab73f703e3d352d2e2b89effb672caa35ff20c/build-openssl-with-msvc.bat#L7)):*
> ```Batchfile
>   no-camellia ^
>   no-cast ^
>   no-dso ^
> ```

are `no-cast`, `no-camellia` and `no-dso` removed/invalid options or why are they no longer present? We still have some of them in the `Makefile` which controls the other platform builds, and there it works :thinking:

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[build-openssl-with-msvc.bat, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-LlW4Tdt7L0k_JrkD3oA:-LlW7AbV9vedQhgZbG9r:bwicz31) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccab73f703e3d352d2e2b89effb672caa35ff20c/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

are `no-cast`, `no-camellia` and `no-dso` removed/invalid options or why are they no longer present? We still have some of them in the `Makefile` which controls the other platform builds, and there it works :thinking: 
</blockquote></details>

Can't find any trace of `dso` in the documentation, but indeed we can still disable `cast` and `camellia` algorithms during build time. I'll try and build it and test it and commit it if everything works.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[build-openssl-with-msvc.bat, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-LlW4Tdt7L0k_JrkD3oA:-LlWBZWHANtdG_GtHkFZ:b-9gc5tn) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccab73f703e3d352d2e2b89effb672caa35ff20c/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Can't find any trace of `dso` in the documentation, but indeed we can still disable `cast` and `camellia` algorithms during build time. I'll try and build it and test it and commit it if everything works.
</blockquote></details>

It builds just fine and the resulting binary works as expected! I've pushed all the changes.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[build-openssl-with-msvc.bat, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-LlW4Tdt7L0k_JrkD3oA:-LlWFmjg2exjklPz-_2Z:bgj0m1z) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccab73f703e3d352d2e2b89effb672caa35ff20c/build-openssl-with-msvc.bat#L7)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It builds just fine and the resulting binary works as expected! I've pushed all the changes.
</blockquote></details>

Great. We should disable as much as possible of the stuff we don't need.
___
*[build-openssl-with-msvc.bat, line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-LlWFdvT2hhKjONHRblO:-LlWFdvT2hhKjONHRblP:b-gsgnza) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccab73f703e3d352d2e2b89effb672caa35ff20c/build-openssl-with-msvc.bat#L5)):*
> ```Batchfile
> set OPENSSL_CONFIG =   enable-capieng ^
>   enable-rfc3779 ^
>   no-camellia ^
> ```

Is it really just `camelia` and not `camellia`? In the `Makefile` we also have double L.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[build-openssl-with-msvc.bat, line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-LlWFdvT2hhKjONHRblO:-LlWKZ5h4WopoZgaizjx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ccab73f703e3d352d2e2b89effb672caa35ff20c/build-openssl-with-msvc.bat#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is it really just `camelia` and not `camellia`? In the `Makefile` we also have double L.
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/37#-:-LlWL7ie9fk2w5rOhSWm:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @faern)

**Pull request merged**
