### PR TITLE
Add to the readme info about how to bump submodules

### PR DESCRIPTION
**Pull request by faern**
When we bump the submodules to new releases it's important that we keep the security tight. For one, we should only point to valid releases, and not random commits between releases, as they might not be stable or good. Secondly, we must verify that the tags on said releases are properly signed by the developers, to avoid getting bad code into these critical components.

Please help me double check the key fingerprints added to the readme. The single commit in this PR is signed. So you can verify that the signatures added to the document actually comes from me.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
Of all the submodules we have, only `lz4` is pointing to a signed commit.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49#-:-LtitUzV0IWIBR87GgAG:b6e5558)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by faern — COMMENTED** [review]
The rest point to signed *tags*, which indeed is the way more common way to promise integrity of a release. Or at least they look signed to me. Could you verify that we currently point to signed tags with the key signatures I wrote about in this document?

> ... These submodules must point to commits that are either directly signed or has a signed tag attached to them...

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49#-:-Ltiyagn8dLfKO7TC_qi:beebj76)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @pinkisemils)

___
*[README.md, line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49#-Ltnv7BX18gUhiBswQEQ:-Ltnv7BX18gUhiBswQER:b-x8cn2r) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/7c81d42bc986bc5eeb432ae15664ee14b5969e85/README.md#L99)):*
> ```Markdown
> 
> ```
> 8657ABB260F056B1E5190839D9C4D26D0E604491
> ```

Not sure about the other submodules, but some tags for OpenSSL are signed by other people. Eg https://git.openssl.org/?p=openssl.git;a=tag;h=61d3564aa3f1633d76c64d67a5e6cc1ebbd79e4b

https://www.openssl.org/community/omc.html

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49#-Ltnv7BX18gUhiBswQEQ:-Ltxps5R4bIU88F8Pb9R:b-dkh7ff) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/7c81d42bc986bc5eeb432ae15664ee14b5969e85/README.md#L99)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not sure about the other submodules, but some tags for OpenSSL are signed by other people. Eg https://git.openssl.org/?p=openssl.git;a=tag;h=61d3564aa3f1633d76c64d67a5e6cc1ebbd79e4b

https://www.openssl.org/community/omc.html
</blockquote></details>

That's a very old tag. We don't need to verify releases we don't use. We only need to be able to verify releases we will move the submodule to. As such, this key is what we need now. And we can use it until they decide to change signer, at that point we can find and verify the new key.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
