### PR TITLE
Add tap-windows6 submodule

### PR DESCRIPTION
**Pull request by dlon**
This adds the submodule [tap-windows6](https://github.com/mullvad/tap-windows6) as well as instructions for how to build the TAP adapter driver. Currently, the script does not copy the build artifacts to where the used ndis6 driver is currently stored (`./x86_64-pc-windows-msvc/driver/ndis6`), because there are manual steps involved in the signing process on Windows 10.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[openvpn, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57#-Lz6M1kyB2o-9z5SnMF2:-Lz6M1kyB2o-9z5SnMF3:b-dc8jur) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/66bb082b9913d7bff446a1461504176171b244b7/openvpn#L1)):*
> ```
> Subproject commit 85f5d0044b2d86d8f5fca81d16bb4d16e2aea7aa
> ```

When this PR is ready for merging, and we have verified that this is indeed what we want. Then make sure to advance the `mullvad-fork` branch in the `openvpn` repo to this new commit. We should also re-issue the signed tag, but I can do that.
___
*[README.md, line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57#-Lz6L2-_BaDKovRlgMC0:-Lz6L2-b-uY4an2YJ595:badcyyz) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/66bb082b9913d7bff446a1461504176171b244b7/README.md#L76)):*
> ```Markdown
> * Visual Studio 2019 (e.g. Build Tools)
> * Spectre-mitigated MSVC libraries (available in the VS installer)
> * Python
> ```

Python 2.7 or 3? Makes quite a difference. If possible to choose then python 3 should be preferred since the former is deprecated (but still widely used :( ).
___
*[tap-windows6, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57#-Lz6ML5lDq3gJcQV0Ffq:-Lz6ML5lDq3gJcQV0Ffr:bf27qmi) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/66bb082b9913d7bff446a1461504176171b244b7/tap-windows6#L1)):*
> ```
> Subproject commit abdb2b4a7184da24dfbfcc057fc5c17b7f454b8c
> ```

Before actually signing a build from this commit we should try to gather more proof that the code we got from github is legitimate. They don't have any signed tags or commits anywhere in the repo.
I submitted this issue to them to request that: https://github.com/OpenVPN/tap-windows6/issues/101

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[README.md, line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57#-Lz6L2-_BaDKovRlgMC0:-Lz6xuWs2AUnW72BCWGG:b-dd7l5q) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/66bb082b9913d7bff446a1461504176171b244b7/README.md#L76)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Python 2.7 or 3? Makes quite a difference. If possible to choose then python 3 should be preferred since the former is deprecated (but still widely used :( ).
</blockquote></details>

Judging from the `print` functions, it is intended for Python 3.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 87 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57#-LzlZ_tK-1QSzW6jKlU8:-LzlZ_tK-1QSzW6jKlU9:b-rd6xwk) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/63c1b6f49f45eea6e2cfbcbe55af24a3f9753acc/README.md#L87)):*
> ```Markdown
> 1. Run (from the `tap-windows6` directory):
>    ```
>    build.bat <cert_sha1_hash>
> ```

Would be good to add some explaining text how to find this. Since we learned today that it was not obvious.

Add a text saying this is the SHA1 hash/thumbprint of the EV certificate and how to find it (certmgr.msc -> Personal -> Can't remember). The important part is saying that it's called the "Thumbprint" in the Windows certificate manager.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, 20 of 20 files at r9, 18 of 20 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: 19 of 23 files reviewed, all discussions resolved (waiting on @faern)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 22 files at r10, 1 of 20 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @faern)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 22 files at r12, 3 of 20 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: 5 of 23 files reviewed, all discussions resolved (waiting on @faern)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 20 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: 6 of 23 files reviewed, all discussions resolved (waiting on @faern)

**Review by faern — APPROVED** [review]
> Reviewed 1 of 22 files at r12, 16 of 20 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/57#-:-Lzqre9N702J4wocobMR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
