### PR TITLE
Support Android 21 API

### PR DESCRIPTION
**Pull request by jvff**
This PR changes the build procedure for Android binaries so that it targets Android API 21. Previously it was targeting API 28, which limits the number of supported devices.

Binaries were rebuilt.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31)

### CODE REVIEW

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/libwg.h, line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31#-LjpzYoI18lS6QLKKg-a:-LjpzYoI18lS6QLKKg-b:bfev0ga) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/2b8856fca1c1abd97410a3d0c01b09d170787089/android/libwg.h#L0)):*
I included this file because it was generated by the build, but I'm not sure if it should be left here or not :thinking:

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31#-:-Ljq-6MS4ouz7eS1mePG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/libwg.h, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31#-LjpzYoI18lS6QLKKg-a:-Ljq0DCa2HcRRS-iYXQ1:b-6yb9pq) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/2b8856fca1c1abd97410a3d0c01b09d170787089/android/libwg.h#L)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I included this file because it was generated by the build, but I'm not sure if it should be left here or not :thinking: 
</blockquote></details>

If we don't need it we should not commit it IMO. Would any other part of the build process reference this header? If not, don't commit it.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/libwg.h, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31#-LjpzYoI18lS6QLKKg-a:-Ljq0Nvm5-Ax0w_5KduO:b-o8ajwe) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/2b8856fca1c1abd97410a3d0c01b09d170787089/android/libwg.h#L)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If we don't need it we should not commit it IMO. Would any other part of the build process reference this header? If not, don't commit it.
</blockquote></details>

We should stay as minimal as possible. So we don't have files laying around that we don't know where they came from or why they are there :)

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[android/libwg.h, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31#-LjpzYoI18lS6QLKKg-a:-Ljq1hEk8dxlcKsyiRBS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/2b8856fca1c1abd97410a3d0c01b09d170787089/android/libwg.h#L)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should stay as minimal as possible. So we don't have files laying around that we don't know where they came from or why they are there :)
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/31)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Pull request merged**
