### PR TITLE
Move binaries to target triplet directories

### PR DESCRIPTION
**Pull request by jvff**
This PR changes the repository structure so that the binaries aren't stored in generic OS-specific directories, but in target-specific directories that include the platform architecture in its name.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
Awesome work! I say :lgtm: under the condition that we have verified it builds on all platforms. Ask if you need help testing on some of them.

> Reviewed 53 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-:-LjrgZ_l5KIGok8CKeJ4:b-rjoydp)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[README.md, line 174 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-LjrfC7R1Wclun3cCM3Q:-LjrfC7SEJ-LZe7clELY:bc2ftwp) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f3f7868fd889217c6efc146f143e253db9d53db/README.md#L174)):*
> ```Markdown
> * `x86_64-unknown-linux-gnu/`
> * `x86_64-apple-darwin/`
> * `x86_64-pc-windows-msvc/`
> ```

This list will grow. I don't see the need/benefit to maintain an updated list of platforms here. We could save ourselves some trouble by just rewording it to "These exist under directories named after the target triplet they are intended for" or something similar. If anyone want to see which platforms we have, they can just look in the submodule directory.
___
*[android-build/build.sh, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-Ljrfmf3-m0aISyiQ8iu:-Ljrfmf3-m0aISyiQ8iv:bk7422b) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f3f7868fd889217c6efc146f143e253db9d53db/android-build/build.sh#L16)):*
> ```Shell
> mkdir -p ../aarch64-linux-android/include/openssl
> cp lib{crypto,ssl}.a ../aarch64-linux-android/
> cp include/openssl/openssl{conf,v}.h ../aarch64-linux-android/include/openssl/
> ```

Seems like a lot of the scripts repeat these triplets quite a lot. Would it not be an improvement to define some `TARGET=aarch64-linux-android` at the top of the script or similar? We will need to do something like this as soon as we support multiple android targets anyway so might as well factor it out now?

**Review by jvff — COMMENTED** [review]
Thanks! The only tests I ran was pushing a test branch on the main repo, and seeing if the CI was still building the app correctly. After fixing a few issues, it seems to be building correctly.

Probably a good idea for us to actually test the final compiled app, though. I can do that tomorrow morning.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-:-Ljs8duK6BRZSJQ2Fy02:bwv3bfc)* status: 52 of 53 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[README.md, line 174 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-LjrfC7R1Wclun3cCM3Q:-Ljs3kZfAczjC7LEIwrY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f3f7868fd889217c6efc146f143e253db9d53db/README.md#L174)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This list will grow. I don't see the need/benefit to maintain an updated list of platforms here. We could save ourselves some trouble by just rewording it to "These exist under directories named after the target triplet they are intended for" or something similar. If anyone want to see which platforms we have, they can just look in the submodule directory.
</blockquote></details>

Done.
___
*[android-build/build.sh, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-Ljrfmf3-m0aISyiQ8iu:-Ljs1pyt492oWH2iLOAH:banpg0i) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f3f7868fd889217c6efc146f143e253db9d53db/android-build/build.sh#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Seems like a lot of the scripts repeat these triplets quite a lot. Would it not be an improvement to define some `TARGET=aarch64-linux-android` at the top of the script or similar? We will need to do something like this as soon as we support multiple android targets anyway so might as well factor it out now?
</blockquote></details>

This will be changed in the next PR, which builds for four separate target triplets, so some environment variables are set up for that.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android-build/build.sh, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-Ljrfmf3-m0aISyiQ8iu:-LjtxX6uA6uPUCZaTLEk:bdwsnuv) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f3f7868fd889217c6efc146f143e253db9d53db/android-build/build.sh#L16)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This will be changed in the next PR, which builds for four separate target triplets, so some environment variables are set up for that.
</blockquote></details>

Ok, cool. Let's save that refactor for the next PR then :+1:

**Review by jvff — COMMENTED** [review]
Tested the app on Windows and it works correctly. On Linux, the binaries need to be updated, so I'll wait for the new binaries.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-:-LjvRub--Ao9Y-lzENwM:b-tltr0x)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — COMMENTED** [review]
With the updated binaries it worked on Linux :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/32#-:-LjwYgSyDWMndBCjt5FH:b2sm0o9)* status: 50 of 53 files reviewed, all discussions resolved (waiting on @faern)

**Pull request merged**
