### PR TITLE
Bootstrap repo for building on three desktop platforms

### PR DESCRIPTION
**Pull request by faern**
Ok, so here we go. The diff is not large. But maybe it's a lot to grasp in one go anyway. I had to kind of make it work on all platforms before I felt it was worth submitting anything, so everything came in one go.

The plan is to build the binaries for the three platforms and commit them to this repo, under the separate directories `macos/`, `linux/` and `windows/`. Then replace the `client-binaries` subrepo of `mullvadvpn-app` with this repo and make Electron builder take the binaries from here. At least that is my plan. Open for suggestions.

What is not done yet, and must be done before I build the actual binaries and commit them:
* @jvff should backport his AUTH_FAILED and reason setting code to our new `mullvad-patches` branch on our OpenVPN fork. We should review that backporting and merge it into `mullvad-patches` and update this submodule to that new commit. Is that code "production ready"?
* At the moment the Windows build, using `openvpn-build`, builds vanilla 2.4.6 OpenVPN. I'm going to make it use our submodule, but did not get to that yet, did not want the PR to blow up too much.

Please also have a look at the stuff I was forced to change in `openvpn-builder` since our own fork of that repo is used here: https://github.com/OpenVPN/openvpn-build/compare/master...mullvad:mullvad-patches
I did these changes to be able to disable pkcs11 support and to make it not download and build stuff we don't need.

To use this repo and these makefiles you should just have to run `make` on Linux and macOS to make it create `build/sbin/openvpn` for you, that should be statically linked and work out of the box.

To build the Windows exe you will have to cross compile from a recent Debian or Ubuntu machine. First run `setup-generic-buildsystem.6.sh` (installs the cross compile toolchain) and then run `make windows`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[Makefile, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-3pcN-kkJ8QF7DBuQ:-LC-3pcN-kkJ8QF7DBuR:b-l1vxi6) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L22)):*
> ```Makefile
> UNAME_S := $(shell uname -s)
> ifeq ($(UNAME_S),Linux)
> 	MAKE_EXTRA_ARGS += LIBS="-all-static"
> ```

On Linux I was not able to get a fully static binary without this option. But on macOS I can't have this option since it looks like it has to be dynamically linked against at least the system libraries. It will still link statically to OpenSSL etc without this on macOS.

---

*[Makefile, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-4-pF5dIfaMEATsiC:-LC-4-pF5dIfaMEATsiD:b-ya35rb) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L23)):*
> ```Makefile
> ifeq ($(UNAME_S),Linux)
> 	MAKE_EXTRA_ARGS += LIBS="-all-static"
> 	OPENSSL_CONFIG += -static
> ```

Kind of the same as above. Without this Linux produces dynamic executables and on macOS I can't build with this option.

---

*[setup-generic-buildsystem.6.sh, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-4GJR4dj5o_wa4xTs:-LC-4GJTAov8vIcfE2ck:bufa4wu) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/setup-generic-buildsystem.6.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

This script is just copied from https://community.openvpn.net/openvpn/wiki/SettingUpGenericBuildsystem#no1

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by faern** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-4nXo6WS5kGo98LEz:-LC-4nXo6WS5kGo98LF-:bvqroh8) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L5)):*
> ```Makefile
> 
> OPENSSL_CONFIG = no-weak-ssl-ciphers no-ssl3 no-ssl3-method no-bf no-rc2 no-rc4 no-rc5 \
> 	no-md4 no-seed no-cast no-camellia no-idea enable-ec_nistp_64_gcc_128 enable-rfc3779
> ```

I'm trying to disable everything that we don't specifically need. In order to reduce compile time, file size and to mitigate downgrade attacks and other problems where the wrong crypto is accidentally used.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by jvff** [comment]
Really nice to have cross-compilation working :thumbsup: 

I can backport the `AUTH_FAIL` changes and test them. Afterwards I'll open a pull request.

---

Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[Makefile, line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-9zQN6vsyWdpTn32y:-LC-9zQT4i7Jl2ZS3XWf:bn0nhtt) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L67)):*
> ```Makefile
> 	make install_sw
> 
> build/sbin/openvpn: build/lib/liblz4.a build/lib/liblzo2.a build/lib/libssl.a build/lib/libcrypto.a
> ```

I'm a little unsure about this dependency specification. Let's say I checkout out a version, and build. That works fine. Then I checkout a different commit that includes changes to the OpenVPN source code. Will this rule be executed? I might be mistaken, but I think it might not, because the timestamps of the dependency library files will stay the same (older than the binary timestamp).

I'm not sure what would be the correct solution, but maybe using phony targets?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-:-LC-B26V10RTBcNfbpZ0:b-tsfh38)*

**Comment by faern** [comment]
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[Makefile, line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-9zQN6vsyWdpTn32y:-LC-L37d8hPtWNK1zD22:b-ne04eg) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L67)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm a little unsure about this dependency specification. Let's say I checkout out a version, and build. That works fine. Then I checkout a different commit that includes changes to the OpenVPN source code. Will this rule be executed? I might be mistaken, but I think it might not, because the timestamps of the dependency library files will stay the same (older than the binary timestamp).

I'm not sure what would be the correct solution, but maybe using phony targets?
</blockquote></details>

I didn't design this to be able to nicely handle incremental compilation or anything like that. My plan was that if one wan't to rebuild anything they should probably just `rm -rf build/`. These dependencies were mostly a way to make it trigger all the dependencies before building OpenVPN itself. Didn't want to try to be too fancy.

Building this will be very seldom. More or less just once per OpenVPN release, maybe even more seldom. But if you have improvement suggestions I'm all ears. It's just that I value simplicity over advanced functionality here I think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by pinkisemils** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[lzo-2.10.tar.gz, line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-5uQ66eDv-J5e-ZDc:-LC-5uQ66eDv-J5e-ZDd:b-ip77wo) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/lzo-2.10.tar.gz#L0)):*
Should this be here if we've got `lz4` as a submodule?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by faern** [comment]
Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[lzo-2.10.tar.gz, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-5uQ66eDv-J5e-ZDc:-LC-VDD3DKUTc1dlhJ7D:b1asc32) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/lzo-2.10.tar.gz#L)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this be here if we've got `lz4` as a submodule?
</blockquote></details>

I could not find any `liblzo` git repository, so the tarball was the only source I could find.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lzo-2.10.tar.gz, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-5uQ66eDv-J5e-ZDc:-LC-g19iAg8npKKqnnH8:b-867vxu) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/lzo-2.10.tar.gz#L)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I could not find any `liblzo` git repository, so the tarball was the only source I could find.
</blockquote></details>

Indeed, it's been a long day.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lzo-2.10.tar.gz, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-5uQ66eDv-J5e-ZDc:-LC00eNC2GB0slyFQ690:b-lvc2tx) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/lzo-2.10.tar.gz#L)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Indeed, it's been a long day.
</blockquote></details>

Those libraries have very similar names indeed ;)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-9zQN6vsyWdpTn32y:-LC0DjyQ3K7B1lNlA7XH:b1jk1ra) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L67)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I didn't design this to be able to nicely handle incremental compilation or anything like that. My plan was that if one wan't to rebuild anything they should probably just `rm -rf build/`. These dependencies were mostly a way to make it trigger all the dependencies before building OpenVPN itself. Didn't want to try to be too fancy.

Building this will be very seldom. More or less just once per OpenVPN release, maybe even more seldom. But if you have improvement suggestions I'm all ears. It's just that I value simplicity over advanced functionality here I think.
</blockquote></details>

I believe these changes would work: https://gist.github.com/jvff/2f2f9bf37a986a293ce95d3f24331158

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by faern** [comment]
Added a `KERNEL_BITS` to make it not warn on macOS. Better to be explicit as well to not accidentally compile the wrong thing.

---

Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC-9zQN6vsyWdpTn32y:-LC2kUWs5JclAjikBnhd:bsr84ml) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/d236c015f4a9752e91a460cad4ae1a9f5bc86ccd/Makefile#L67)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I believe these changes would work: https://gist.github.com/jvff/2f2f9bf37a986a293ce95d3f24331158
</blockquote></details>

I applied your changes, but with slightly different target names. Thanks for the suggestions :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-:-LC2lGtm1DrqK1e1FTD_:b-ptgkul)*

**Comment by faern** [comment]
Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[Makefile, line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-LC2m_EfAPJnYlDjeQ1j:-LC2m_EfAPJnYlDjeQ1k:bxaewyr) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5b67badca222b7b16e35f9988793998f3f775641/Makefile#L42)):*
> ```Makefile
> 	cd lz4 ; \
> 	$(MAKE) clean ; \
> 	PREFIX=$(BUILD_DIR) $(MAKE) install $(MAKE_EXTRA_ARGS)
> ```

The make step before this that I just removed was not needed. `make install` triggers exactly what that `make` call did anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Comment by jvff** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-:-LC3FQ30786ATdTIDp70:bnfp4nl)*

**Comment by faern** [comment]
By request from @richard-mullvad I added HTTP proxy support. Seems to work.

---

Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-:-LC3bFr26CXFlDPiJSFO:b98txqp)*

**Comment by pinkisemils** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2#-:-LC3fzip7q5QvUdpy5eQ:bnfp4nl)*

**Comment by richard-mullvad** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/2)*

**Pull request merged**
