### PR TITLE
Update Openssl to 3.0.8

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Upgrade `OpenSSL` to 3.0.8, since 1.1.1 which we currently depend on reaches EOL in september.

`OpenSSL` builds just fine by running `/container-run.sh make openssl`, but please verify/comment if there is more to bumping this dependency than what currently goes in the PR commit :blush:

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
Does OpenVPN compile and work with 3.0?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-:-NWhpP_gAdRuaUcb7nnm:b-vtjt3x)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`Makefile` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-NWhprS59ppA39b3syM1:-NWhprS59ppA39b3syM2:b-bh10kt) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/29a4c7205e78c651fcd1b8c3a55181c0d86a50d3/Makefile#L10)):*
> ```Makefile
> OPENSSL_CONFIGURE_SCRIPT = ./config
> OPENSSL_VERSION = 1.1.1t
> OPENSSL_CONFIG = no-weak-ssl-ciphers no-ssl3 no-ssl3-method no-bf no-rc2 no-rc4 no-rc5 \
> ```

Are all of these options still valid?

**Review by MarkusPettersson98 — COMMENTED** [review]
Work: Yes. See https://openvpn.net/blog/openvpn-2-6/
Compile: Not yet, running into an error at the moment: `configure: error: openssl check failed`

Hope that I will get it to work soon :blush: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-:-NWpyzujCrQX_bhIusgb:blk9z9k)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`Makefile` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-NWhprS59ppA39b3syM1:-NWpwYVI8oTHje2M2kx8:bmirt0z) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/29a4c7205e78c651fcd1b8c3a55181c0d86a50d3/Makefile#L10)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are all of these options still valid?
</blockquote></details>

I've gone through the options and cross-checked them with the migration guide for users of OpenSSL 1.1.1: https://www.openssl.org/docs/man3.0/man7/migration_guide.html
I did not find any indication that any option (or combination of options) should cause any issues :blush:

**Comment by MarkusPettersson98** [comment]
Now OpenVPN compiles fine with OpenSSL 3.0.8!
The problem was that the output folder for the OpenSSL libraries changed from `lib` to `lib64` :sweat_smile:

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-:-NX6tbuL8xLS-jrZ_XFc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`.gitmodules` line 10 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal9BgWAjgKhJPucdox:-Nal9BgX72XEKMxTSx3j:b49oftq) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/.gitmodules#L10)):*
> ```gitconfig
> 	path = openvpn-build
> 	url = https://github.com/mullvad/openvpn-build.git
> 	branch = mullvad-patches
> ```

Is this really needed? We have been running custom branches on this submodule repo since forever, but never needed the `branch` directive here :thinking: 
___
*[`Makefile` line 68 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal9UQY1zIIPNb5WOrS:-Nal9UQY1zIIPNb5WOrT:b-6dga9k) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/Makefile#L68)):*
> ```Makefile
> 
> ifeq ($(TARGET),x86_64-apple-darwin)
> 	MACOSX_DEPLOYMENT_TARGET = "11.0"
> ```

I'm not sure this should be 11.0. This variable is now set *three* times in this makefile. I'm sure we should be able to get by with at most two. And for x86_64 I believe this can be kept at 10.13? Not that our main app supports that old macOS any longer, but anyway. If it needs to be bumped we can do that, but then the the 10.13 above should be removed/rewritten in some way.
___
*[`Makefile` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-NalBGu717PKPigWFrFe:-NalBGu717PKPigWFrFf:b-92p5fe) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/Makefile#L74)):*
> ```Makefile
> 		CFLAGS = -arch x86_64 -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
> 		LDFLAGS = -arch x86_64 -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
> 		PLATFORM_OPENVPN_CONFIG = --host=x86_64-apple-darwin
> ```

These five lines are more or less just duplicates of the code above for the cross compilation the other way around. Can we make this shorter/smarter without losing readability? I'm thinking something like the following in the global scope:

```
ifeq ($(UNAME_S),Darwin)
	# Host is different than target. Need to configure cross compilation
	ifneq ($(HOST),$(TARGET))
		OPENSSL_CONFIGURE_SCRIPT = ./Configure
		PLATFORM_OPENSSL_CONFIG += darwin64-$(UNAME_M)-cc
		CFLAGS = -arch $(UNAME_M) -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
		LDFLAGS = -arch $(UNAME_M) -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
		PLATFORM_OPENVPN_CONFIG = --host=$(TARGET)
	endif
endif
```
___
*[`openvpn-build` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal7vqT7PBjhmVrLcGW:-Nal7vqU13c0qUT27WL8:brxrcr7) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/openvpn-build#L1)):*
> ```
> Subproject commit be187e4ff14299d48f1370bcd0acbead3799cbb9
> ```

You (I) will also need to push a signed tag to this commit. Otherwise this commit will *not exist* in some future where the `mullvad-patches` branch might move. We need to future protect ourselves with tags to make github keep those commits.

I suggest you (I) just *move* the tag `OpenVPN-2.6.0-I004-mullvad` to your new preferred main commit here. Since that commit is the child of the old commit the old commit will be guaranteed to be kept in the tree if a child is kept.
___
*[`README.md` line 56 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal94FB5NC5kFGrSlT8:-Nal94FB5NC5kFGrSlT9:b-h6twru) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/README.md#L56)):*
> ```Markdown
> ```
> 
> Building the OpenVPN binary should be as simple as running:
> ```

Maybe add "... for the current architecture ..." in here to be clearer?
___
*[`README.md` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal8XfG5oRgYukfcTKZ:-Nal8XfG5oRgYukfcTK_:beecng1) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/README.md#L74)):*
There is a lot of duplication here. We were having some of this before this PR also, but it becomes more now. What I want to get rid of is:

> To do the thing just append VERY_LONG_AND_COMPLICATED_ARGUMENT:
> make openvpn VERY_LONG_AND_COMPLICATED_ARGUMENT

And just specify that once. See if you can condense these docs without losing important information.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dlon and @faern)

___
*[`.gitmodules` line 10 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal9BgWAjgKhJPucdox:-NalGpJQ6hRjLh1voEjX:b-vm5sga) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/.gitmodules#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is this really needed? We have been running custom branches on this submodule repo since forever, but never needed the `branch` directive here :thinking: 
</blockquote></details>

No, it is not necessary. The `openvpn-build` submodule points to be187e4ff14299d48f1370bcd0acbead3799cbb9 anyway :)
___
*[`Makefile` line 68 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal9UQY1zIIPNb5WOrS:-NalHberE3JXYirKR7Ks:b-l1ramn) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/Makefile#L68)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure this should be 11.0. This variable is now set *three* times in this makefile. I'm sure we should be able to get by with at most two. And for x86_64 I believe this can be kept at 10.13? Not that our main app supports that old macOS any longer, but anyway. If it needs to be bumped we can do that, but then the the 10.13 above should be removed/rewritten in some way.
</blockquote></details>

`MACOSX_DEPLOYMENT_TARGET` is now only set when the target platform is known, so the number of times the variable is set is reduced to 2.
___
*[`Makefile` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-NalBGu717PKPigWFrFe:-NalIXxZ0GbhaCw-nElz:b-1i75b6) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/Makefile#L74)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These five lines are more or less just duplicates of the code above for the cross compilation the other way around. Can we make this shorter/smarter without losing readability? I'm thinking something like the following in the global scope:

```
ifeq ($(UNAME_S),Darwin)
	# Host is different than target. Need to configure cross compilation
	ifneq ($(HOST),$(TARGET))
		OPENSSL_CONFIGURE_SCRIPT = ./Configure
		PLATFORM_OPENSSL_CONFIG += darwin64-$(UNAME_M)-cc
		CFLAGS = -arch $(UNAME_M) -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
		LDFLAGS = -arch $(UNAME_M) -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
		PLATFORM_OPENVPN_CONFIG = --host=$(TARGET)
	endif
endif
```
</blockquote></details>

Neat suggestion! But `$(UNAME_M)` can't be used to configure appropriate `CFLAGS` & `LDFLAGS` for the target :/ What I did instead was to de-duplicate some lines by grouping them under "global scope" (when the host is macos). I code generalize more I guess, but it would become a bit code-golfy imho. Please let me know if you still think I should generalize :) 
___
*[`openvpn-build` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal7vqT7PBjhmVrLcGW:-NalVI0NB_adgvMk1GDD:b-px0gks) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/openvpn-build#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You (I) will also need to push a signed tag to this commit. Otherwise this commit will *not exist* in some future where the `mullvad-patches` branch might move. We need to future protect ourselves with tags to make github keep those commits.

I suggest you (I) just *move* the tag `OpenVPN-2.6.0-I004-mullvad` to your new preferred main commit here. Since that commit is the child of the old commit the old commit will be guaranteed to be kept in the tree if a child is kept.
</blockquote></details>

That sounds like a good idea. :D

Let me know if I should act on this, otherwise I will leave this step up to you. The commit to use from the [mullvad/openvpn-build repo](https://github.com/mullvad/openvpn-build) is be187e4ff14299d48f1370bcd0acbead3799cbb9 :blush: 
___
*[`README.md` line 56 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal94FB5NC5kFGrSlT8:-NalSb353-TeWQFb_9sG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/README.md#L56)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe add "... for the current architecture ..." in here to be clearer?
</blockquote></details>

Done.
___
*[`README.md` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal8XfG5oRgYukfcTKZ:-NalV4T09WhHZcrfxR-9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/README.md#L74)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

There is a lot of duplication here. We were having some of this before this PR also, but it becomes more now. What I want to get rid of is:

> To do the thing just append VERY_LONG_AND_COMPLICATED_ARGUMENT:
> make openvpn VERY_LONG_AND_COMPLICATED_ARGUMENT

And just specify that once. See if you can condense these docs without losing important information.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`README.md` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal8XfG5oRgYukfcTKZ:-Nap9STC2gUu8zmdGfJA:b1wgp77) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/README.md#L74)):*
Much better! Only nitpicking left. I would maybe condense it even further. I feel like the following does not lose any information, is faster to read, and reduce some header-overload that we currently seem to have :D

> ...
> ```
> make openvpn
> ```
>
> #### Cross compiling
>
> To compile for another architecture than your host's, just supply the `TARGET` argument:
> 
> ```
> make openvpn TARGET="x86_64-apple-darwin"
> make openvpn TARGET="aarch64-apple-darwin"
> ```
___
*[`README.md` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nap9pLf3dEbNhWnUgqU:-Nap9pLf3dEbNhWnUgqV:b-u51t1e) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/89c58e21f98ad3857f2eeb6d9e62e77486903c22/README.md#L62)):*
> ```Markdown
> ```
> 
> ##### Cross compiling (arm64 ↔ x86)
> ```

This header is one level too low? The header above it is just `###`

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`openvpn-build` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nal7vqT7PBjhmVrLcGW:-NapMAY5DUbJ6Y5zJNg8:b-50tcou) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/ad222f4819330a0d22402349ecbcb4c38f59c3fa/openvpn-build#L1)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

That sounds like a good idea. :D

Let me know if I should act on this, otherwise I will leave this step up to you. The commit to use from the [mullvad/openvpn-build repo](https://github.com/mullvad/openvpn-build) is be187e4ff14299d48f1370bcd0acbead3799cbb9 :blush: 
</blockquote></details>

I have moved the tag now :+1:

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`README.md` line 93 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105#-Nap_ms8EX5fZ5fn6g40:-Nap_ms8EX5fZ5fn6g41:bc41422) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0c288fb431e8dbc890dcbf7b2dcdf0ce5bf5fadb/README.md#L93)):*
> ```Markdown
> 
> 1. Sign `openvpn.exe` - Do this by copying `openvpn.exe` to the Windows machine with
>    the certificate and run:
> ```

Not directly related to this PR, but would help avoid creating a separate PR for a tiny thing: Can you please add that this must be run in powershell? :pray:

**Review by faern — APPROVED** [review]
> Reviewed 5 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/105)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
