### PR TITLE
Create a Dockerfile to build binaries for Android

### PR DESCRIPTION
**Pull request by jvff**
This PR adds Android binaries for `libwg-go` and also sets up a Dockerfile to be used for cross-compiling the Android binaries.

The `Makefile` was updated to include targets to use the Dockerfile to build the Docker image with the cross-compiled binaries, and to extract those binaries into the repository. The `clean` target was also updated to remove the created Docker images.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @faern, @jvff, and @pinkisemils)

___
*[android.dockerfile, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-Leqc6x_4kAgFu_dpIcn:-Leqc6xa4Jv560BzFR8D:bb1brz2) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/87c2be59818b3da1f0f40dc7fde01f4c5099e46a/android.dockerfile#L15)):*
> ```Dockerfile
>     echo "%sudo ALL = (ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudo_group
> 
> USER user
> ```

I suppose there is a good reason for this, but I'm not fluent in docker so I have to ask: Why do we create a separate user, grant it sudo access and then use that user with sudo, instead of just performing the entire build as root?
___
*[android.dockerfile, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-Leqh3mV3jTDy_2eLAJt:-Leqh3mV3jTDy_2eLAJu:bxmml03) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/87c2be59818b3da1f0f40dc7fde01f4c5099e46a/android.dockerfile#L21)):*
> ```Dockerfile
>     sudo mkdir /opt/android && \
>     cd /opt/android && \
>     sudo unzip -q /tmp/android-ndk-r19b-linux-x86_64.zip && \
> ```

Do we want to remove the zip after unpacking it? I suppose that would make the resulting image smaller?
___
*[Makefile, line 185 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-Leq_iXH5DeXLyJ4sWQf:-Leq_iXI6gpHLVQN-GAV:b-1tb52r) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/87c2be59818b3da1f0f40dc7fde01f4c5099e46a/Makefile#L185)):*
> ```Makefile
> android-build: android.dockerfile
> 	@echo "Building binaries for Android"
> 	docker build --force-rm -t mullvad/mullvadvpn-app-android-binaries -f ./android.dockerfile .
> ```

I think the two target names `android-build` and `android` are quite ambiguous, can they get more descriptive names? Or do we even ever want to be able to call one but not the other? Can't both docker commands be joined under a single `android` make target?

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[android.dockerfile, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-Leqc6x_4kAgFu_dpIcn:-LeqjDkM5lt3Dt6QNEr4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/87c2be59818b3da1f0f40dc7fde01f4c5099e46a/android.dockerfile#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I suppose there is a good reason for this, but I'm not fluent in docker so I have to ask: Why do we create a separate user, grant it sudo access and then use that user with sudo, instead of just performing the entire build as root?
</blockquote></details>

Done.
___
*[android.dockerfile, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-Leqh3mV3jTDy_2eLAJt:-LeqjaTLDetdLFJtz1Tr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/87c2be59818b3da1f0f40dc7fde01f4c5099e46a/android.dockerfile#L21)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do we want to remove the zip after unpacking it? I suppose that would make the resulting image smaller?
</blockquote></details>

Done.
___
*[Makefile, line 185 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-Leq_iXH5DeXLyJ4sWQf:-Lerxkly8ANPzLQcGSIU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/87c2be59818b3da1f0f40dc7fde01f4c5099e46a/Makefile#L185)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think the two target names `android-build` and `android` are quite ambiguous, can they get more descriptive names? Or do we even ever want to be able to call one but not the other? Can't both docker commands be joined under a single `android` make target?
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @faern, @jvff, and @pinkisemils)

___
*[Makefile, line 183 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-LesLe_lA9Zg_bBnU0Zr:-LesLe_lA9Zg_bBnU0Zs:bpxj002) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f02f07bcf4d49a487f0de3e9381aa3f5b47b11e/Makefile#L183)):*
> ```Makefile
> 	cp shadowsocks-rust/target/release/sslocal $(TARGET_OUTPUT_DIR)/
> 
> android: android-build/Dockerfile android-build/build.bash
> ```

How does these dependencies work? Those paths don't have any make targets. And they are not produced by make, they are always present in the repo :thinking: 
___
*[android-build/Dockerfile, line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-LesKyYb-oCAZ6YAdad1:-LesKyYb-oCAZ6YAdad2:baktnbb) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f02f07bcf4d49a487f0de3e9381aa3f5b47b11e/android-build/Dockerfile#L45)):*
> ```Dockerfile
> ENV PATH=${PATH}:/opt/go/bin
> 
> COPY build.bash /usr/local/bin/build.bash
> ```

Why the `.bash` file extension? I don't think I have ever seen that. All our other bash scripts in this and all other repos are `.sh` files.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[Makefile, line 183 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-LesLe_lA9Zg_bBnU0Zr:-LeudjIN6QL2_2L3DMuK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f02f07bcf4d49a487f0de3e9381aa3f5b47b11e/Makefile#L183)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

How does these dependencies work? Those paths don't have any make targets. And they are not produced by make, they are always present in the repo :thinking: 
</blockquote></details>

Done.
___
*[android-build/Dockerfile, line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-LesKyYb-oCAZ6YAdad1:-LeudjkC7k40mB9lSELZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/5f02f07bcf4d49a487f0de3e9381aa3f5b47b11e/android-build/Dockerfile#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why the `.bash` file extension? I don't think I have ever seen that. All our other bash scripts in this and all other repos are `.sh` files.
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

___
*[android-build/Dockerfile, line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-LevPYRO0YmkE2rgUrux:-LevPYRO0YmkE2rgUruy:blv0qun) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/7399e15ca7e31e19c19880f05f9ba37bb4365710/android-build/Dockerfile#L1)):*
> ```Dockerfile
> FROM debian@sha256:75f7d0590b45561bfa443abad0b3e0f86e2811b1fc176f786cd30eb078d1846f
> ```

Niiiice! Is this our own reproducible builds? Or just the hash for the official vanilla debian image?

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

___
*[android-build/Dockerfile, line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-LevPYRO0YmkE2rgUrux:-LevRguQDvknobKaAXlz:b-odmetm) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/7399e15ca7e31e19c19880f05f9ba37bb4365710/android-build/Dockerfile#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Niiiice! Is this our own reproducible builds? Or just the hash for the official vanilla debian image?
</blockquote></details>

This is just the vanilla debian image :/

**Review by faern — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19#-:-Lev_8Tf7nK6rlXj1NXh:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/19)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
