### PR TITLE
Add apisocks5 binaries for the desktop OSes

### PR DESCRIPTION
**Pull request by faern**
Built from `main` in this repo on our build servers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/110)

### CODE REVIEW

**Review by hulthe — APPROVED** [review]
lgtm :moneybag: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/110#-:-NyZqqx93suXjWxqaaKN:b3y6ngh)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by dlon** [comment]
@faern Should `apisocks5.exe` be signed here?

**Comment by faern** [comment]
@dlon Aah. Yes, it probably should. Did not have a thought about it. But it would be beneficial. Then I'll have to wait until next week to sign it and merge this.

**Comment by raksooo** [comment]
I've now signed `apisocks5.exe` and amended it to the previous commit.

**Review by hulthe — APPROVED** [review]

**Pull request merged**
