### PR TITLE
Support multiple Android architectures

### PR DESCRIPTION
**Pull request by jvff**
This PR changes the Android build procedure to produce binaries for the four main platform architectures: x86-64, x86, Arm v7 (32-bit) and Arm v8 (64-bit).

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
I'll try and have a closer look tomorrow, but from a late-night glance, it looks good!

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-:-LjwmEcY9te2EpkDs-GS:b-x8due4)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @faern, @jvff, and @pinkisemils)

___
*[android-build/Dockerfile, line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjwlPv5AildaUq6UqQK:-LjwlPv5AildaUq6UqQL:b-fzhqkz) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/Dockerfile#L38)):*
> ```Dockerfile
>         for lib in crtbegin_dynamic.o crtend_android.o crtbegin_so.o crtend_so.o; do \
>             ln -s "/opt/android/toolchains/android21-${arch}/sysroot/usr/lib/${TARGET}/21/$lib" /opt/android/toolchains/android21-${arch}/sysroot/usr/lib/${TARGET}/; \
>         done \
> ```

Gotta love these hacks :joy: 
___
*[armv7-linux-androideabi/include/openssl/opensslconf.h, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-Ljwlry27KYFmsnK9j9P:-Ljwlry27KYFmsnK9j9Q:bp02r3b) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/armv7-linux-androideabi/include/openssl/opensslconf.h#L1)):*
> ```objc
> /*
> ```

Does `openssl-sys` parse these headers?

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 13 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34)* status: 13 of 18 files reviewed, 4 unresolved discussions (waiting on @faern, @jvff, and @pinkisemils)

___
*[android-build/build.sh, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjyZwRFBNsBDQMK3jG7:-LjyZwRG8UR8W9_XhmE9:b-4icdar) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L8)):*
> ```Shell
>     case "$arch" in
>         "arm64")
>             export ANDROID_ARCH_NAME="arm64"
> ```

This variable is set to the same value as `$arch` in all cases from what I can see. Is it not possible to move it outside the `case` and just set it like
```bash
export  ANDROID_ARCH_NAME="$arch"
```
? Or maybe make the loop go over it directly
```bash
for ANDROID_ARCH_NAME in arm arm64 x86_64 x86; do
```
? But maybe the latter does not properly export it to subsequent subshells if it's needed there.
___
*[android-build/build.sh, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjyaU5Z8pppwN5rjxrk:-LjyaU5_3xIXIoB7MkzZ:b-1xl7w4) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L50)):*
> ```Shell
>         export OPENSSL_CONFIG="$COMMON_OPENSSL_CONFIG enable-ec_nistp_64_gcc_128"
>     else
>         export OPENSSL_CONFIG="$COMMON_OPENSSL_CONFIG"
> ```

Instead of having both `COMMON_OPENSSL_CONFIG` and `OPENSSL_CONFIG` can't you just have `OPENSSL_CONFIG` and conditionally append to the same variable. Would require one variable name less to keep track of and no else case in this if

```bash
OPENSSL_CONFIG="no-weak-ssl-ciphers ...."
if echo "$ANDROID_ARCH_NAME" | grep -q 64; then
    OPENSSL_CONFIG+=" enable-ec_nistp_64_gcc_128"
fi
```
?

Not sure if the `export` part is really needed? You only use it locally to pass it to `./Configure` below, right?
___
*[android-build/build.sh, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjycBUu0EjXd4OvWJab:-LjycBUu0EjXd4OvWJac:b-v7pd3r) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L70)):*
> ```Shell
>     export LDFLAGS="-L${ANDROID_SYSROOT}/usr/lib/${ANDROID_LIB_TRIPLE}/21"
> 
>     make -f Android.mk
> ```

Is this wireguard build picking up target information from the environment variables exported above? Or how does it know which platform to build for?
___
*[armv7-linux-androideabi/include/openssl/opensslconf.h, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-Ljwlry27KYFmsnK9j9P:-LjyekJI2vX-TCczY-br:bkfejw) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/armv7-linux-androideabi/include/openssl/opensslconf.h#L1)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Does `openssl-sys` parse these headers?
</blockquote></details>

Exactly... :/ 

https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/main.rs#L107-L123

https://github.com/sfackler/rust-openssl/blob/5faeeb5c6151e6d87a1e303797d0d5892bc51719/openssl-sys/build/expando.c#L1-L2

**Review by faern — COMMENTED** [review]
> Reviewed 5 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34)* status: all files reviewed, 4 unresolved discussions (waiting on @jvff and @pinkisemils)

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[android-build/build.sh, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjyZwRFBNsBDQMK3jG7:-LjzwPLF5vwVedMXTmk5:b-2pxq9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L8)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This variable is set to the same value as `$arch` in all cases from what I can see. Is it not possible to move it outside the `case` and just set it like
```bash
export  ANDROID_ARCH_NAME="$arch"
```
? Or maybe make the loop go over it directly
```bash
for ANDROID_ARCH_NAME in arm arm64 x86_64 x86; do
```
? But maybe the latter does not properly export it to subsequent subshells if it's needed there.
</blockquote></details>

Done. Used the first option so that it's still exported so Wireguard-Go's makefile can use it.
___
*[android-build/build.sh, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjzyNtD7OcYUNNiI3vK:-LjzyNtD7OcYUNNiI3vL:b-5ltbku) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L40)):*
> ```Shell
>     export ANDROID_SYSROOT="${ANDROID_TOOLCHAIN_ROOT}/sysroot"
>     export ANDROID_C_COMPILER="${ANDROID_TOOLCHAIN_ROOT}/bin/${ANDROID_LLVM_TRIPLE}21-clang"
>     export OPENSSL_ARCH="android-${ANDROID_ARCH_NAME}"
> ```

FYI, also removed this variable because it was only used once.
___
*[android-build/build.sh, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjyaU5Z8pppwN5rjxrk:-LjzwGX63Joh1mbuGb_G:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L50)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Instead of having both `COMMON_OPENSSL_CONFIG` and `OPENSSL_CONFIG` can't you just have `OPENSSL_CONFIG` and conditionally append to the same variable. Would require one variable name less to keep track of and no else case in this if

```bash
OPENSSL_CONFIG="no-weak-ssl-ciphers ...."
if echo "$ANDROID_ARCH_NAME" | grep -q 64; then
    OPENSSL_CONFIG+=" enable-ec_nistp_64_gcc_128"
fi
```
?

Not sure if the `export` part is really needed? You only use it locally to pass it to `./Configure` below, right?
</blockquote></details>

Done.
___
*[android-build/build.sh, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-LjycBUu0EjXd4OvWJab:-LjztH6nDmm-2eN3hOP-:b-t3y9kg) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/0b8c2cdd14fdac14fc6e1536adeeed541f40ceea/android-build/build.sh#L70)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is this wireguard build picking up target information from the environment variables exported above? Or how does it know which platform to build for?
</blockquote></details>

Yes, it uses some of the exported environment variables.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/34#-:-Ljzz9ZrCLHzRD6N3nom:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
